/* XPM */
static char *alg0[] = {
/* columns rows colors chars-per-pixel */
"60 60 15",
"c 0x000000",
". 0x2D3B4D",
"X 0x36475C",
"o 0x3D5068",
"O 0x435873",
"+ 0x495F7C",
"@ 0x536C8D",
"# 0x577294",
"$ 0x5B779B",
"% 0x5F7CA1",
"& 0x6281A7",
"* 0x6685AD",
"= 0x6989B3",
"- 0x6C8EB8",
"; 0x7092BE",
/* pixels */
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccc$-;;;;;;;;;;;;;;;;;;;@cccccccccccccccccc",
"ccccccccccccccccccco;;;;;;;;;;;;;;;;;;;;;;Occccccccccccccccc",
"ccccccccccccccccccc$;;;;;;;;;;;;;;;;;;;;;;$ccccccccccccccccc",
"cccccccccccccccccc.;;;;;;;;;;;;;;;;;;;;;;;-.cccccccccccccccc",
"ccccccccccccccccO$-;;;;;;;;;;;;;;;;;;;;;;;;-#occcccccccccccc",
"ccccccccccccccc@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;$ccccccccccccc",
"ccccccccccccccc;;;;;;;;;*@OOOOOOOOO+$=;;;;;;;;-ccccccccccccc",
"ccccccccccccccc;;;;;;;;=cccccccccccccc*;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;#cccccccccccccc@;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;Occc+*****%.cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;Occ.;;;;;;;&cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccO;;;;;;;;cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccO;;;;;;;;cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccO;;;;;;;;cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccO;;;;;;;;cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccO;;;;;;;;cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccO;;;;;;;;cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccO;;;;;;;;cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccO;;;;;;;;cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccO;;;;;;;;cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccO;;;;;;;;cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccO;;;;;;;;cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccO;;;;;;;;cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccO;;;;;;;;cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccO;;;;;;;;cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccX;;;;;;;&cccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;Occc+*****&XcccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;OccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;@cccccccccccccc$;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;*cccccccccccccc=;;;;;;;;ccccccccccccc",
"ccccccccccccccc;;;;;;;;;=#OOOOOOOOOO#-;;;;;;;;;ccccccccccccc",
"ccccccccccccccc$;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@ccccccccccccc",
"cccccccccccccccco#-;;;;;;;;;;;;;;;;;;;;;;;;-$Occcccccccccccc",
"cccccccccccccccccc.-;;;;;;;;;;;;;;;;;;;;;;;.cccccccccccccccc",
"ccccccccccccccccccc$;;;;;;;;;;;;;;;;;;;;;;$ccccccccccccccccc",
"cccccccccccccccccccO;;;;;;;;;;;;;;;;;;;;;;occccccccccccccccc",
"cccccccccccccccccccc#;;;;;;;;;;;;;;;;;;;-#cccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
};


/* XPM */
static char *alg1[] = {
/* columns rows colors chars-per-pixel */
"60 60 10",
"c 0x000000",
". 0x3D5068",
"X 0x435873",
"o 0x495F7C",
"O 0x577294",
"+ 0x5B779B",
"@ 0x6281A7",
"# 0x6989B3",
"$ 0x6C8EB8",
"% 0x7092BE",
/* pixels */
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccc.$%%%%%%%%%%+ccccccccccccccccccccccccccc",
"cccccccccccccccccccc#%%%%%%%%%%%%occcccccccccccccccccccccccc",
"cccccccccccccccccccc%%%%%%%%%%%%%Occcccccccccccccccccccccccc",
"cccccccccccccccccccc%%%%%%%%%%%%%Occcccccccccccccccccccccccc",
"cccccccccccccccccccc%%%%%%%%%%%%%Occcccccccccccccccccccccccc",
"cccccccccccccccccccc+%%%%%%%%%%%%Occcccccccccccccccccccccccc",
"cccccccccccccccccccccX+#%%%%%%%%%Occcccccccccccccccccccccccc",
"cccccccccccccccccccccccc@%%%%%%%%Occcccccccccccccccccccccccc",
"cccccccccccccccccccccccc.%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc%%%%%%%%Occcccccccccccccccccccccccc",
"ccccccccccccccccccccccccc$%%%%%%%.cccccccccccccccccccccccccc",
"ccccccccccccccccccccccccc.#%%%%%+ccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
};


/* XPM */
static char *alg2[] = {
/* columns rows colors chars-per-pixel */
"60 60 14",
"c 0x000000",
". 0x2D3B4D",
"X 0x3D5068",
"o 0x435873",
"O 0x4E6685",
"+ 0x536C8D",
"@ 0x577294",
"# 0x5B779B",
"$ 0x5F7CA1",
"% 0x6281A7",
"& 0x6685AD",
"* 0x6989B3",
"= 0x6C8EB8",
"- 0x7092BE",
/* pixels */
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccX-------------------------#ccccccccccccccccc",
"cccccccccccccccc&--------------------------occcccccccccccccc",
"cccccccccccccccc---------------------------#cccccccccccccccc",
"cccccccccccccccc---------------------------=.ccccccccccccccc",
"cccccccccccccccc----------------------------=+Xccccccccccccc",
"cccccccccccccccc@------------------------------+cccccccccccc",
"cccccccccccccccccX@@@@@@@@@@@@@@@@@@@#=--------=cccccccccccc",
"cccccccccccccccccccccccccccccccccccccc.=--------cccccccccccc",
"ccccccccccccccccccccccccccccccccccccccc@--------cccccccccccc",
"ccccccccccccccccccccccccccccccccccccccco--------cccccccccccc",
"ccccccccccccccccccccccccccccccccccccccco--------cccccccccccc",
"ccccccccccccccccccccccccccccccccccccccco--------cccccccccccc",
"ccccccccccccccccccccccccccccccccccccccco--------cccccccccccc",
"ccccccccccccccccccccccccccccccccccccccco--------cccccccccccc",
"ccccccccccccccccccccccccccccccccccccccco--------cccccccccccc",
"cccccccccccccccccccccccccccccccccccccccO--------cccccccccccc",
"ccccccccccccccccccccccccccccccccccccccc%--------cccccccccccc",
"ccccccccccccccccccccccccccccccccccccc.+---------cccccccccccc",
"ccccccccccccccccccccc#=------------------------%cccccccccccc",
"ccccccccccccccccccccX-------------------------$.cccccccccccc",
"cccccccccccccccccccc#-----------------------occccccccccccccc",
"ccccccccccccccccccc.=----------------------$cccccccccccccccc",
"ccccccccccccccccco#=-----------------------Occcccccccccccccc",
"cccccccccccccccc+-------------------------*ccccccccccccccccc",
"cccccccccccccccc---------&@ooooooooooooooocccccccccccccccccc",
"cccccccccccccccc--------*ccccccccccccccccccccccccccccccccccc",
"cccccccccccccccc--------+ccccccccccccccccccccccccccccccccccc",
"cccccccccccccccc--------occccccccccccccccccccccccccccccccccc",
"cccccccccccccccc--------occccccccccccccccccccccccccccccccccc",
"cccccccccccccccc--------occccccccccccccccccccccccccccccccccc",
"cccccccccccccccc--------occccccccccccccccccccccccccccccccccc",
"cccccccccccccccc--------occccccccccccccccccccccccccccccccccc",
"cccccccccccccccc--------occccccccccccccccccccccccccccccccccc",
"cccccccccccccccc--------+ccccccccccccccccccccccccccccccccccc",
"cccccccccccccccc--------=ccccccccccccccccccccccccccccccccccc",
"cccccccccccccccc=--------=#@@@@@@@@@@@@@@@@@@@Xccccccccccccc",
"cccccccccccccccc+------------------------------@cccccccccccc",
"cccccccccccccccccX+=----------------------------cccccccccccc",
"ccccccccccccccccccc.=---------------------------cccccccccccc",
"cccccccccccccccccccc#---------------------------cccccccccccc",
"cccccccccccccccccccco--------------------------&cccccccccccc",
"ccccccccccccccccccccc#-------------------------Xcccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
};


/* XPM */
static char *alg3[] = {
/* columns rows colors chars-per-pixel */
"60 60 16",
"c 0x000000",
". 0x2D3B4D",
"X 0x36475C",
"o 0x3D5068",
"O 0x435873",
"+ 0x495F7C",
"@ 0x4E6685",
"# 0x536C8D",
"$ 0x577294",
"% 0x5B779B",
"& 0x5F7CA1",
"* 0x6281A7",
"= 0x6685AD",
"- 0x6989B3",
"; 0x6C8EB8",
": 0x7092BE",
/* pixels */
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccX=:::::::::::::::::::::::;@cccccccccccccccccc",
"ccccccccccccccc&::::::::::::::::::::::::::Occccccccccccccccc",
"ccccccccccccccc=::::::::::::::::::::::::::%ccccccccccccccccc",
"ccccccccccccccc=::::::::::::::::::::::::::;.cccccccccccccccc",
"ccccccccccccccc=:::::::::::::::::::::::::::;#occcccccccccccc",
"ccccccccccccccc+::::::::::::::::::::::::::::::$ccccccccccccc",
"cccccccccccccccc.OOOOOOOOOOOOOOOOOOO$-:::::::::ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc=::::::::ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc#::::::::ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO::::::::ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO::::::::ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO::::::::ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO::::::::ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO::::::::ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO::::::::ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc@::::::::ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc*::::::::ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccX$:::::::::ccccccccccccc",
"cccccccccccccccccccc@;::::::::::::::::::::::::=ccccccccccccc",
"cccccccccccccccccccc:::::::::::::::::::::::::*.ccccccccccccc",
"cccccccccccccccccccO:::::::::::::::::::::::*.ccccccccccccccc",
"cccccccccccccccccccO:::::::::::::::::::::::@cccccccccccccccc",
"ccccccccccccccccccco::::::::::::::::::::::::@.cccccccccccccc",
"cccccccccccccccccccc-:::::::::::::::::::::::::@ccccccccccccc",
"cccccccccccccccccccc.@$$$$$$$$$$$$$$&:::::::::;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccc.;::::::::ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc$::::::::ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO::::::::ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO::::::::ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO::::::::ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO::::::::ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO::::::::ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO::::::::ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc%::::::::ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc;::::::::ccccccccccccc",
"cccccccccccccccco$$$$$$$$$$$$$$$$$$$%;:::::::::ccccccccccccc",
"ccccccccccccccc@::::::::::::::::::::::::::::::@ccccccccccccc",
"ccccccccccccccc=:::::::::::::::::::::::::::;$occcccccccccccc",
"ccccccccccccccc=::::::::::::::::::::::::::;.cccccccccccccccc",
"ccccccccccccccc=::::::::::::::::::::::::::%ccccccccccccccccc",
"ccccccccccccccc*::::::::::::::::::::::::::occccccccccccccccc",
"ccccccccccccccco=::::::::::::::::::::::::%cccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
};


/* XPM */
static char *alg4[] = {
/* columns rows colors chars-per-pixel */
"60 60 14",
"c 0x000000",
". 0x2D3B4D",
"X 0x3D5068",
"o 0x435873",
"O 0x4E6685",
"+ 0x536C8D",
"@ 0x577294",
"# 0x5B779B",
"$ 0x5F7CA1",
"% 0x6281A7",
"& 0x6685AD",
"* 0x6989B3",
"= 0x6C8EB8",
"- 0x7092BE",
/* pixels */
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccX=----=Occcccccccccccccc+-----*Xccccccccccccc",
"ccccccccccccccc%-------Xcccccccccccccc.-------*ccccccccccccc",
"ccccccccccccccc--------occcccccccccccco--------ccccccccccccc",
"ccccccccccccccc--------occcccccccccccco--------ccccccccccccc",
"ccccccccccccccc--------occcccccccccccco--------ccccccccccccc",
"ccccccccccccccc--------occcccccccccccco--------ccccccccccccc",
"ccccccccccccccc--------occcccccccccccco--------ccccccccccccc",
"ccccccccccccccc--------occcccccccccccco--------ccccccccccccc",
"ccccccccccccccc--------occcccccccccccco--------ccccccccccccc",
"ccccccccccccccc--------occcccccccccccco--------ccccccccccccc",
"ccccccccccccccc--------occcccccccccccco--------ccccccccccccc",
"ccccccccccccccc--------occcccccccccccco--------ccccccccccccc",
"ccccccccccccccc--------occcccccccccccco--------ccccccccccccc",
"ccccccccccccccc--------occcccccccccccco--------ccccccccccccc",
"ccccccccccccccc--------occcccccccccccco--------ccccccccccccc",
"ccccccccccccccc--------Occcccccccccccc+--------ccccccccccccc",
"ccccccccccccccc--------$cccccccccccccc%--------ccccccccccccc",
"ccccccccccccccc---------#XccccccccccX@---------ccccccccccccc",
"ccccccccccccccc%-------------------------------ccccccccccccc",
"ccccccccccccccc.#=-----------------------------ccccccccccccc",
"cccccccccccccccccco----------------------------ccccccccccccc",
"ccccccccccccccccccc%---------------------------ccccccccccccc",
"cccccccccccccccccccO---------------------------ccccccccccccc",
"ccccccccccccccccccc.*--------------------------ccccccccccccc",
"cccccccccccccccccccc.O@@@@@@@@@@@@@@#=---------ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc=--------ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc+--------ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccco--------ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccco--------ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccco--------ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccco--------ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccco--------ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccco--------ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccco--------ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccco--------ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccco--------ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccco--------ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccco--------ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccco--------ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccco--------ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccX-------&ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccc+=----=Xccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
};


/* XPM */
static char *alg5[] = {
/* columns rows colors chars-per-pixel */
"60 60 14",
"c 0x000000",
". 0x2D3B4D",
"X 0x3D5068",
"o 0x435873",
"O 0x4E6685",
"+ 0x536C8D",
"@ 0x577294",
"# 0x5B779B",
"$ 0x5F7CA1",
"% 0x6281A7",
"& 0x6685AD",
"* 0x6989B3",
"= 0x6C8EB8",
"- 0x7092BE",
/* pixels */
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccX-----------------------------*Xcccccccccccccc",
"cccccccccccccc&------------------------------*cccccccccccccc",
"cccccccccccccc--------------------------------cccccccccccccc",
"cccccccccccccc--------------------------------cccccccccccccc",
"cccccccccccccc-------------------------------=cccccccccccccc",
"cccccccccccccc-------------------------------@cccccccccccccc",
"cccccccccccccc---------=#@@@@@@@@@@@@@@@@@@@Xccccccccccccccc",
"cccccccccccccc--------=.cccccccccccccccccccccccccccccccccccc",
"cccccccccccccc--------#ccccccccccccccccccccccccccccccccccccc",
"cccccccccccccc--------occccccccccccccccccccccccccccccccccccc",
"cccccccccccccc--------occccccccccccccccccccccccccccccccccccc",
"cccccccccccccc--------occccccccccccccccccccccccccccccccccccc",
"cccccccccccccc--------occccccccccccccccccccccccccccccccccccc",
"cccccccccccccc--------occccccccccccccccccccccccccccccccccccc",
"cccccccccccccc--------occccccccccccccccccccccccccccccccccccc",
"cccccccccccccc--------Occccccccccccccccccccccccccccccccccccc",
"cccccccccccccc--------$ccccccccccccccccccccccccccccccccccccc",
"cccccccccccccc---------+.ccccccccccccccccccccccccccccccccccc",
"cccccccccccccc%-------------------------@ccccccccccccccccccc",
"cccccccccccccc.#=------------------------occcccccccccccccccc",
"ccccccccccccccccco-----------------------#cccccccccccccccccc",
"cccccccccccccccccc$----------------------=.ccccccccccccccccc",
"ccccccccccccccccccO-----------------------=@Xccccccccccccccc",
"ccccccccccccccccccc*-------------------------#cccccccccccccc",
"ccccccccccccccccccccooooooooooooooo+*--------=cccccccccccccc",
"ccccccccccccccccccccccccccccccccccccc&--------cccccccccccccc",
"ccccccccccccccccccccccccccccccccccccc+--------cccccccccccccc",
"ccccccccccccccccccccccccccccccccccccco--------cccccccccccccc",
"ccccccccccccccccccccccccccccccccccccco--------cccccccccccccc",
"ccccccccccccccccccccccccccccccccccccco--------cccccccccccccc",
"ccccccccccccccccccccccccccccccccccccco--------cccccccccccccc",
"ccccccccccccccccccccccccccccccccccccco--------cccccccccccccc",
"ccccccccccccccccccccccccccccccccccccco--------cccccccccccccc",
"ccccccccccccccccccccccccccccccccccccc#--------cccccccccccccc",
"cccccccccccccccccccccccccccccccccccc.=--------cccccccccccccc",
"cccccccccccccccX@@@@@@@@@@@@@@@@@@@#=---------cccccccccccccc",
"cccccccccccccc@------------------------------Occcccccccccccc",
"cccccccccccccc=---------------------------=@Xccccccccccccccc",
"cccccccccccccc---------------------------=.ccccccccccccccccc",
"cccccccccccccc---------------------------#cccccccccccccccccc",
"cccccccccccccc*--------------------------Xcccccccccccccccccc",
"ccccccccccccccX*------------------------#ccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
};


/* XPM */
static char *alg6[] = {
/* columns rows colors chars-per-pixel */
"60 60 13",
"c 0x000000",
". 0x2D3B4D",
"X 0x3D5068",
"o 0x435873",
"O 0x4E6685",
"+ 0x536C8D",
"@ 0x577294",
"# 0x5B779B",
"$ 0x5F7CA1",
"% 0x6685AD",
"& 0x6989B3",
"* 0x6C8EB8",
"= 0x7092BE",
/* pixels */
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccc#*=======================&Xcccccccccccccc",
"ccccccccccccccccccX==========================&cccccccccccccc",
"cccccccccccccccccc#===========================cccccccccccccc",
"ccccccccccccccccc.============================cccccccccccccc",
"ccccccccccccccco#*===========================*cccccccccccccc",
"cccccccccccccc+==============================Occcccccccccccc",
"cccccccccccccc=========&@oooooooooooooooooooXccccccccccccccc",
"cccccccccccccc========&ccccccccccccccccccccccccccccccccccccc",
"cccccccccccccc========#ccccccccccccccccccccccccccccccccccccc",
"cccccccccccccc========occccccccccccccccccccccccccccccccccccc",
"cccccccccccccc========occccccccccccccccccccccccccccccccccccc",
"cccccccccccccc========occccccccccccccccccccccccccccccccccccc",
"cccccccccccccc========occccccccccccccccccccccccccccccccccccc",
"cccccccccccccc========occccccccccccccccccccccccccccccccccccc",
"cccccccccccccc========occccccccccccccccccccccccccccccccccccc",
"cccccccccccccc========Occccccccccccccccccccccccccccccccccccc",
"cccccccccccccc========$ccccccccccccccccccccccccccccccccccccc",
"cccccccccccccc=========+.ccccccccccccccccccccccccccccccccccc",
"cccccccccccccc==========================@ccccccccccccccccccc",
"cccccccccccccc===========================occcccccccccccccccc",
"cccccccccccccc===========================#cccccccccccccccccc",
"cccccccccccccc===========================*.ccccccccccccccccc",
"cccccccccccccc============================*@Xccccccccccccccc",
"cccccccccccccc===============================#cccccccccccccc",
"cccccccccccccc=========%@oooooooooo+&========*cccccccccccccc",
"cccccccccccccc========&cccccccccccccc%========cccccccccccccc",
"cccccccccccccc========+cccccccccccccc+========cccccccccccccc",
"cccccccccccccc========occcccccccccccco========cccccccccccccc",
"cccccccccccccc========occcccccccccccco========cccccccccccccc",
"cccccccccccccc========occcccccccccccco========cccccccccccccc",
"cccccccccccccc========occcccccccccccco========cccccccccccccc",
"cccccccccccccc========occcccccccccccco========cccccccccccccc",
"cccccccccccccc========occcccccccccccco========cccccccccccccc",
"cccccccccccccc========+cccccccccccccc#========cccccccccccccc",
"cccccccccccccc========*ccccccccccccc.*========cccccccccccccc",
"cccccccccccccc*========*#@@@@@@@@@@#*=========cccccccccccccc",
"cccccccccccccc+==============================Occcccccccccccc",
"cccccccccccccccX+*========================*@Xccccccccccccccc",
"ccccccccccccccccc.*======================*.ccccccccccccccccc",
"cccccccccccccccccc#======================#cccccccccccccccccc",
"cccccccccccccccccco======================Xcccccccccccccccccc",
"ccccccccccccccccccc#====================#ccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
};


/* XPM */
static char *alg7[] = {
/* columns rows colors chars-per-pixel */
"60 60 15",
"c 0x000000",
". 0x2D3B4D",
"X 0x36475C",
"o 0x3D5068",
"O 0x435873",
"+ 0x495F7C",
"@ 0x4E6685",
"# 0x536C8D",
"$ 0x577294",
"% 0x5B779B",
"& 0x5F7CA1",
"* 0x6685AD",
"= 0x6989B3",
"- 0x6C8EB8",
"; 0x7092BE",
/* pixels */
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccX*;;;;;;;;;;;;;;;;;;;;;;;-@cccccccccccccccccc",
"ccccccccccccccc&;;;;;;;;;;;;;;;;;;;;;;;;;;Occccccccccccccccc",
"ccccccccccccccc*;;;;;;;;;;;;;;;;;;;;;;;;;;%ccccccccccccccccc",
"ccccccccccccccc*;;;;;;;;;;;;;;;;;;;;;;;;;;-.cccccccccccccccc",
"ccccccccccccccc*;;;;;;;;;;;;;;;;;;;;;;;;;;;-#occcccccccccccc",
"ccccccccccccccc+;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;$ccccccccccccc",
"cccccccccccccccc.OOOOOOOOOOOOOOOOOOO$=;;;;;;;;-ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc*;;;;;;;;ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc#;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccO;;;;;;;;ccccccccccccc",
"cccccccccccccccccccccccccccccccccccccco;;;;;;;*ccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccc@-;;;;-occccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
};

/* XPM */
static char *alg8[] = {
/* columns rows colors chars-per-pixel */
"60 60 16",
"c 0x000000",
". 0x2D3B4D",
"X 0x36475C",
"o 0x3D5068",
"O 0x435873",
"+ 0x495F7C",
"@ 0x4E6685",
"# 0x536C8D",
"$ 0x577294",
"% 0x5B779B",
"& 0x5F7CA1",
"* 0x6281A7",
"= 0x6685AD",
"- 0x6989B3",
"; 0x6C8EB8",
": 0x7092BE",
/* pixels */
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccc.@$$$$$$$$$$$$$$$$$$#.ccccccccccccccccc",
"cccccccccccccccccccc.::::::::::::::::::::::.cccccccccccccccc",
"cccccccccccccccccccc@::::::::::::::::::::::#cccccccccccccccc",
"cccccccccccccccccccc=::::::::::::::::::::::*cccccccccccccccc",
"cccccccccccccccccc.#::::::::::::::::::::::::#ccccccccccccccc",
"ccccccccccccccccX=::::::::::::::::::::::::::::*occcccccccccc",
"cccccccccccccccc=::::::::::=========-::::::::::=cccccccccccc",
"cccccccccccccccc:::::::::@ccccccccccc.+:::::::::cccccccccccc",
"cccccccccccccccc::::::::*cccccccccccccc&::::::::cccccccccccc",
"cccccccccccccccc::::::::@cccccccccccccc@::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::@cccccccccccccc#::::::::cccccccccccc",
"cccccccccccccccc::::::::&cccccccccccccc=::::::::cccccccccccc",
"cccccccccccccccc:::::::::%XccccccccccX$:::::::::cccccccccccc",
"cccccccccccccccc*::::::::::::::::::::::::::::::*cccccccccccc",
"cccccccccccccccc.&::::::::::::::::::::::::::::&.cccccccccccc",
"cccccccccccccccccc.*::::::::::::::::::::::::*ccccccccccccccc",
"ccccccccccccccccccc@::::::::::::::::::::::::@ccccccccccccccc",
"cccccccccccccccccX$::::::::::::::::::::::::::$.ccccccccccccc",
"cccccccccccccccc@::::::::::::::::::::::::::::::@cccccccccccc",
"cccccccccccccccc;:::::::::&$$$$$$$$$$&:::::::::;cccccccccccc",
"cccccccccccccccc::::::::;.cccccccccccc.;::::::::cccccccccccc",
"cccccccccccccccc::::::::&cccccccccccccc$::::::::cccccccccccc",
"cccccccccccccccc::::::::+cccccccccccccc+::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::$cccccccccccccc%::::::::cccccccccccc",
"cccccccccccccccc::::::::-cccccccccccccc-::::::::cccccccccccc",
"cccccccccccccccc;::::::::-%OOOOOOOOOO$;:::::::::cccccccccccc",
"cccccccccccccccc%::::::::::::::::::::::::::::::#cccccccccccc",
"ccccccccccccccccco$;::::::::::::::::::::::::;%Occccccccccccc",
"ccccccccccccccccccc.;:::::::::::::::::::::::.ccccccccccccccc",
"cccccccccccccccccccc%::::::::::::::::::::::%cccccccccccccccc",
"ccccccccccccccccccccO::::::::::::::::::::::occcccccccccccccc",
"ccccccccccccccccccccc$:::::::::::::::::::;%ccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
};


/* XPM */
static char *alg9[] = {
/* columns rows colors chars-per-pixel */
"60 60 16",
"c 0x000000",
". 0x2D3B4D",
"X 0x36475C",
"o 0x3D5068",
"O 0x435873",
"+ 0x495F7C",
"@ 0x4E6685",
"# 0x536C8D",
"$ 0x577294",
"% 0x5B779B",
"& 0x5F7CA1",
"* 0x6281A7",
"= 0x6685AD",
"- 0x6989B3",
"; 0x6C8EB8",
": 0x7092BE",
/* pixels */
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccc%::::::::::::::::::::#ccccccccccccccccc",
"cccccccccccccccccccco::::::::::::::::::::::Occcccccccccccccc",
"cccccccccccccccccccc%::::::::::::::::::::::%cccccccccccccccc",
"ccccccccccccccccccc.;::::::::::::::::::::::;cccccccccccccccc",
"cccccccccccccccccX#-::::::::::::::::::::::::=@.ccccccccccccc",
"cccccccccccccccc@::::::::::::::::::::::::::::::@cccccccccccc",
"cccccccccccccccc;::::::::;$OOOOOOOOOO$-::::::::;cccccccccccc",
"cccccccccccccccc::::::::;cccccccccccccc=::::::::cccccccccccc",
"cccccccccccccccc::::::::%cccccccccccccc#::::::::cccccccccccc",
"cccccccccccccccc::::::::+ccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::OccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccc::::::::@cccccccccccccc#::::::::cccccccccccc",
"cccccccccccccccc::::::::&cccccccccccccc*::::::::cccccccccccc",
"cccccccccccccccc:::::::::#.cccccccccc.#:::::::::cccccccccccc",
"cccccccccccccccc*:::::::::::::::::::::::::::::::cccccccccccc",
"cccccccccccccccc.%;:::::::::::::::::::::::::::::cccccccccccc",
"cccccccccccccccccccO::::::::::::::::::::::::::::cccccccccccc",
"cccccccccccccccccccc&:::::::::::::::::::::::::::cccccccccccc",
"cccccccccccccccccccc@:::::::::::::::::::::::::::cccccccccccc",
"ccccccccccccccccccccc-::::::::::::::::::::::::::cccccccccccc",
"ccccccccccccccccccccccOOOOOOOOOOOOOOO#-:::::::::cccccccccccc",
"ccccccccccccccccccccccccccccccccccccccc=::::::::cccccccccccc",
"ccccccccccccccccccccccccccccccccccccccc#::::::::cccccccccccc",
"cccccccccccccccccccccccccccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccccccccccccccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccccccccccccccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccccccccccccccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccccccccccccccccccccccccccO::::::::cccccccccccc",
"cccccccccccccccccccccccccccccccccccccccO::::::::cccccccccccc",
"ccccccccccccccccccccccccccccccccccccccc%::::::::cccccccccccc",
"ccccccccccccccccccccccccccccccccccccccc;::::::::cccccccccccc",
"ccccccccccccccccco$$$$$$$$$$$$$$$$$$$%;:::::::::cccccccccccc",
"cccccccccccccccc$::::::::::::::::::::::::::::::@cccccccccccc",
"cccccccccccccccc;:::::::::::::::::::::::::::;$occccccccccccc",
"cccccccccccccccc:::::::::::::::::::::::::::;.ccccccccccccccc",
"cccccccccccccccc:::::::::::::::::::::::::::%cccccccccccccccc",
"cccccccccccccccc-::::::::::::::::::::::::::occcccccccccccccc",
"cccccccccccccccco-::::::::::::::::::::::::%ccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
};
