/* XPM */
static char *alg0[] = {
/* columns rows colors chars-per-pixel */
"32 42 15",
"c 0x000000",
". 0x2D3B4D",
"X 0x36475C",
"o 0x3D5068",
"O 0x435873",
"+ 0x495F7C",
"@ 0x536C8D",
"# 0x577294",
"$ 0x5B779B",
"% 0x5F7CA1",
"& 0x6281A7",
"* 0x6685AD",
"= 0x6989B3",
"- 0x6C8EB8",
"; 0x7092BE",
/* pixels */
// -9 -9
"ccccc$-;;;;;;;;;;;;;;;;;;;@ccccc",
"cccco;;;;;;;;;;;;;;;;;;;;;;Occcc",
"cccc$;;;;;;;;;;;;;;;;;;;;;;$cccc",
"ccc.;;;;;;;;;;;;;;;;;;;;;;;-.ccc",
"cO$-;;;;;;;;;;;;;;;;;;;;;;;;-#oc",
"@;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;$",
";;;;;;;;;*@OOOOOOOOO+$=;;;;;;;;-",
";;;;;;;;=cccccccccccccc*;;;;;;;;",
";;;;;;;;#cccccccccccccc@;;;;;;;;",
";;;;;;;;OccccccccccccccO;;;;;;;;",
";;;;;;;;OccccccccccccccO;;;;;;;;",
";;;;;;;;OccccccccccccccO;;;;;;;;",
";;;;;;;;Occc+*****%.cccO;;;;;;;;",
";;;;;;;;Occ.;;;;;;;&cccO;;;;;;;;",
";;;;;;;;OccO;;;;;;;;cccO;;;;;;;;",
";;;;;;;;OccO;;;;;;;;cccO;;;;;;;;",
";;;;;;;;OccO;;;;;;;;cccO;;;;;;;;",
";;;;;;;;OccO;;;;;;;;cccO;;;;;;;;",
";;;;;;;;OccO;;;;;;;;cccO;;;;;;;;",
";;;;;;;;OccO;;;;;;;;cccO;;;;;;;;",
";;;;;;;;OccO;;;;;;;;cccO;;;;;;;;",
";;;;;;;;OccO;;;;;;;;cccO;;;;;;;;",
";;;;;;;;OccO;;;;;;;;cccO;;;;;;;;",
";;;;;;;;OccO;;;;;;;;cccO;;;;;;;;",
";;;;;;;;OccO;;;;;;;;cccO;;;;;;;;",
";;;;;;;;OccO;;;;;;;;cccO;;;;;;;;",
";;;;;;;;OccO;;;;;;;;cccO;;;;;;;;",
";;;;;;;;OccO;;;;;;;;cccO;;;;;;;;",
";;;;;;;;OccX;;;;;;;&cccO;;;;;;;;",
";;;;;;;;Occc+*****&XcccO;;;;;;;;",
";;;;;;;;OccccccccccccccO;;;;;;;;",
";;;;;;;;OccccccccccccccO;;;;;;;;",
";;;;;;;;OccccccccccccccO;;;;;;;;",
";;;;;;;;@cccccccccccccc$;;;;;;;;",
";;;;;;;;*cccccccccccccc=;;;;;;;;",
";;;;;;;;;=#OOOOOOOOOO#-;;;;;;;;;",
"$;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;@",
"co#-;;;;;;;;;;;;;;;;;;;;;;;;-$Oc",
"ccc.-;;;;;;;;;;;;;;;;;;;;;;;.ccc",
"cccc$;;;;;;;;;;;;;;;;;;;;;;$cccc",
"ccccO;;;;;;;;;;;;;;;;;;;;;;occcc",
"cccccc#;;;;;;;;;;;;;;;;;;;-#cccc"
};


/* XPM */
static char *alg1[] = {
/* columns rows colors chars-per-pixel */
"32 42 10",
"c 0x000000",
". 0x3D5068",
"X 0x435873",
"o 0x495F7C",
"O 0x577294",
"+ 0x5B779B",
"@ 0x6281A7",
"# 0x6989B3",
"$ 0x6C8EB8",
"% 0x7092BE",
/* pixels */
// -9 -9
"ccccccc.$%%%%%%%%%%+cccccccccccc",
"ccccccc#%%%%%%%%%%%%occccccccccc",
"ccccccc%%%%%%%%%%%%%Occccccccccc",
"ccccccc%%%%%%%%%%%%%Occccccccccc",
"ccccccc%%%%%%%%%%%%%Occccccccccc",
"ccccccc+%%%%%%%%%%%%Occccccccccc",
"ccccccccX+#%%%%%%%%%Occccccccccc",
"ccccccccccc@%%%%%%%%Occccccccccc",
"ccccccccccc.%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc%%%%%%%%Occccccccccc",
"cccccccccccc$%%%%%%%.ccccccccccc",
"cccccccccccc.#%%%%%+cccccccccccc"
};


/* XPM */
static char *alg2[] = {
/* columns rows colors chars-per-pixel */
"32 42 14",
"c 0x000000",
". 0x2D3B4D",
"X 0x3D5068",
"o 0x435873",
"O 0x4E6685",
"+ 0x536C8D",
"@ 0x577294",
"# 0x5B779B",
"$ 0x5F7CA1",
"% 0x6281A7",
"& 0x6685AD",
"* 0x6989B3",
"= 0x6C8EB8",
"- 0x7092BE",
/* pixels */
// -9 -9
"X-------------------------#ccccc",
"&--------------------------occcc",
"---------------------------#cccc",
"---------------------------=.ccc",
"----------------------------=+Xc",
"@------------------------------+",
"cX@@@@@@@@@@@@@@@@@@@#=--------=",
"cccccccccccccccccccccc.=--------",
"ccccccccccccccccccccccc@--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"cccccccccccccccccccccccO--------",
"ccccccccccccccccccccccc%--------",
"ccccccccccccccccccccc.+---------",
"ccccc#=------------------------%",
"ccccX-------------------------$.",
"cccc#-----------------------occc",
"ccc.=----------------------$cccc",
"co#=-----------------------Occcc",
"+-------------------------*ccccc",
"---------&@ooooooooooooooocccccc",
"--------*ccccccccccccccccccccccc",
"--------+ccccccccccccccccccccccc",
"--------occccccccccccccccccccccc",
"--------occccccccccccccccccccccc",
"--------occccccccccccccccccccccc",
"--------occccccccccccccccccccccc",
"--------occccccccccccccccccccccc",
"--------occccccccccccccccccccccc",
"--------+ccccccccccccccccccccccc",
"--------=ccccccccccccccccccccccc",
"=--------=#@@@@@@@@@@@@@@@@@@@Xc",
"+------------------------------@",
"cX+=----------------------------",
"ccc.=---------------------------",
"cccc#---------------------------",
"cccco--------------------------&",
"ccccc#-------------------------X"
};


/* XPM */
static char *alg3[] = {
/* columns rows colors chars-per-pixel */
"32 42 16",
"c 0x000000",
". 0x2D3B4D",
"X 0x36475C",
"o 0x3D5068",
"O 0x435873",
"+ 0x495F7C",
"@ 0x4E6685",
"# 0x536C8D",
"$ 0x577294",
"% 0x5B779B",
"& 0x5F7CA1",
"* 0x6281A7",
"= 0x6685AD",
"- 0x6989B3",
"; 0x6C8EB8",
": 0x7092BE",
/* pixels */
//-9 -9
"X=:::::::::::::::::::::::;@ccccc",
"&::::::::::::::::::::::::::Occcc",
"=::::::::::::::::::::::::::%cccc",
"=::::::::::::::::::::::::::;.ccc",
"=:::::::::::::::::::::::::::;#oc",
"+::::::::::::::::::::::::::::::$",
"c.OOOOOOOOOOOOOOOOOOO$-:::::::::",
"ccccccccccccccccccccccc=::::::::",
"ccccccccccccccccccccccc#::::::::",
"cccccccccccccccccccccccO::::::::",
"cccccccccccccccccccccccO::::::::",
"cccccccccccccccccccccccO::::::::",
"cccccccccccccccccccccccO::::::::",
"cccccccccccccccccccccccO::::::::",
"cccccccccccccccccccccccO::::::::",
"ccccccccccccccccccccccc@::::::::",
"ccccccccccccccccccccccc*::::::::",
"cccccccccccccccccccccX$:::::::::",
"ccccc@;::::::::::::::::::::::::=",
"ccccc:::::::::::::::::::::::::*.",
"ccccO:::::::::::::::::::::::*.cc",
"ccccO:::::::::::::::::::::::@ccc",
"cccco::::::::::::::::::::::::@.c",
"ccccc-:::::::::::::::::::::::::@",
"ccccc.@$$$$$$$$$$$$$$&:::::::::;",
"cccccccccccccccccccccc.;::::::::",
"ccccccccccccccccccccccc$::::::::",
"cccccccccccccccccccccccO::::::::",
"cccccccccccccccccccccccO::::::::",
"cccccccccccccccccccccccO::::::::",
"cccccccccccccccccccccccO::::::::",
"cccccccccccccccccccccccO::::::::",
"cccccccccccccccccccccccO::::::::",
"ccccccccccccccccccccccc%::::::::",
"ccccccccccccccccccccccc;::::::::",
"co$$$$$$$$$$$$$$$$$$$%;:::::::::",
"@::::::::::::::::::::::::::::::@",
"=:::::::::::::::::::::::::::;$oc",
"=::::::::::::::::::::::::::;.ccc",
"=::::::::::::::::::::::::::%cccc",
"*::::::::::::::::::::::::::occcc",
"o=::::::::::::::::::::::::%ccccc"
};


/* XPM */
static char *alg4[] = {
/* columns rows colors chars-per-pixel */
"32 42 14",
"c 0x000000",
". 0x2D3B4D",
"X 0x3D5068",
"o 0x435873",
"O 0x4E6685",
"+ 0x536C8D",
"@ 0x577294",
"# 0x5B779B",
"$ 0x5F7CA1",
"% 0x6281A7",
"& 0x6685AD",
"* 0x6989B3",
"= 0x6C8EB8",
"- 0x7092BE",
/* pixels */
//-9 -9 -15 -13
"X=----=Occcccccccccccccc+-----*X",
"%-------Xcccccccccccccc.-------*",
"--------occcccccccccccco--------",
"--------occcccccccccccco--------",
"--------occcccccccccccco--------",
"--------occcccccccccccco--------",
"--------occcccccccccccco--------",
"--------occcccccccccccco--------",
"--------occcccccccccccco--------",
"--------occcccccccccccco--------",
"--------occcccccccccccco--------",
"--------occcccccccccccco--------",
"--------occcccccccccccco--------",
"--------occcccccccccccco--------",
"--------occcccccccccccco--------",
"--------Occcccccccccccc+--------",
"--------$cccccccccccccc%--------",
"---------#XccccccccccX@---------",
"%-------------------------------",
".#=-----------------------------",
"ccco----------------------------",
"cccc%---------------------------",
"ccccO---------------------------",
"cccc.*--------------------------",
"ccccc.O@@@@@@@@@@@@@@#=---------",
"ccccccccccccccccccccccc=--------",
"ccccccccccccccccccccccc+--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"cccccccccccccccccccccccX-------&",
"cccccccccccccccccccccccc+=----=X"
};


/* XPM */
static char *alg5[] = {
/* columns rows colors chars-per-pixel */
"32 42 14",
"c 0x000000",
". 0x2D3B4D",
"X 0x3D5068",
"o 0x435873",
"O 0x4E6685",
"+ 0x536C8D",
"@ 0x577294",
"# 0x5B779B",
"$ 0x5F7CA1",
"% 0x6281A7",
"& 0x6685AD",
"* 0x6989B3",
"= 0x6C8EB8",
"- 0x7092BE",
/* pixels */
"X-----------------------------*X",
"&------------------------------*",
"--------------------------------",
"--------------------------------",
"-------------------------------=",
"-------------------------------@",
"---------=#@@@@@@@@@@@@@@@@@@@Xc",
"--------=.cccccccccccccccccccccc",
"--------#ccccccccccccccccccccccc",
"--------occccccccccccccccccccccc",
"--------occccccccccccccccccccccc",
"--------occccccccccccccccccccccc",
"--------occccccccccccccccccccccc",
"--------occccccccccccccccccccccc",
"--------occccccccccccccccccccccc",
"--------Occccccccccccccccccccccc",
"--------$ccccccccccccccccccccccc",
"---------+.ccccccccccccccccccccc",
"%-------------------------@ccccc",
".#=------------------------occcc",
"ccco-----------------------#cccc",
"cccc$----------------------=.ccc",
"ccccO-----------------------=@Xc",
"ccccc*-------------------------#",
"ccccccooooooooooooooo+*--------=",
"ccccccccccccccccccccccc&--------",
"ccccccccccccccccccccccc+--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccco--------",
"ccccccccccccccccccccccc#--------",
"cccccccccccccccccccccc.=--------",
"cX@@@@@@@@@@@@@@@@@@@#=---------",
"@------------------------------O",
"=---------------------------=@Xc",
"---------------------------=.ccc",
"---------------------------#cccc",
"*--------------------------Xcccc",
"X*------------------------#ccccc"
};


/* XPM */
static char *alg6[] = {
/* columns rows colors chars-per-pixel */
"32 42 13",
"c 0x000000",
". 0x2D3B4D",
"X 0x3D5068",
"o 0x435873",
"O 0x4E6685",
"+ 0x536C8D",
"@ 0x577294",
"# 0x5B779B",
"$ 0x5F7CA1",
"% 0x6685AD",
"& 0x6989B3",
"* 0x6C8EB8",
"= 0x7092BE",
/* pixels */
"ccccc#*=======================&X",
"ccccX==========================&",
"cccc#===========================",
"ccc.============================",
"co#*===========================*",
"+==============================O",
"=========&@oooooooooooooooooooXc",
"========&ccccccccccccccccccccccc",
"========#ccccccccccccccccccccccc",
"========occccccccccccccccccccccc",
"========occccccccccccccccccccccc",
"========occccccccccccccccccccccc",
"========occccccccccccccccccccccc",
"========occccccccccccccccccccccc",
"========occccccccccccccccccccccc",
"========Occccccccccccccccccccccc",
"========$ccccccccccccccccccccccc",
"=========+.ccccccccccccccccccccc",
"==========================@ccccc",
"===========================occcc",
"===========================#cccc",
"===========================*.ccc",
"============================*@Xc",
"===============================#",
"=========%@oooooooooo+&========*",
"========&cccccccccccccc%========",
"========+cccccccccccccc+========",
"========occcccccccccccco========",
"========occcccccccccccco========",
"========occcccccccccccco========",
"========occcccccccccccco========",
"========occcccccccccccco========",
"========occcccccccccccco========",
"========+cccccccccccccc#========",
"========*ccccccccccccc.*========",
"*========*#@@@@@@@@@@#*=========",
"+==============================O",
"cX+*========================*@Xc",
"ccc.*======================*.ccc",
"cccc#======================#cccc",
"cccco======================Xcccc",
"ccccc#====================#ccccc"
};


/* XPM */
static char *alg7[] = {
/* columns rows colors chars-per-pixel */
"32 42 15",
"c 0x000000",
". 0x2D3B4D",
"X 0x36475C",
"o 0x3D5068",
"O 0x435873",
"+ 0x495F7C",
"@ 0x4E6685",
"# 0x536C8D",
"$ 0x577294",
"% 0x5B779B",
"& 0x5F7CA1",
"* 0x6685AD",
"= 0x6989B3",
"- 0x6C8EB8",
"; 0x7092BE",
/* pixels */
"X*;;;;;;;;;;;;;;;;;;;;;;;-@ccccc",
"&;;;;;;;;;;;;;;;;;;;;;;;;;;Occcc",
"*;;;;;;;;;;;;;;;;;;;;;;;;;;%cccc",
"*;;;;;;;;;;;;;;;;;;;;;;;;;;-.ccc",
"*;;;;;;;;;;;;;;;;;;;;;;;;;;;-#oc",
"+;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;$",
"c.OOOOOOOOOOOOOOOOOOO$=;;;;;;;;-",
"ccccccccccccccccccccccc*;;;;;;;;",
"ccccccccccccccccccccccc#;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"cccccccccccccccccccccccO;;;;;;;;",
"ccccccccccccccccccccccco;;;;;;;*",
"cccccccccccccccccccccccc@-;;;;-o"
};

/* XPM */
static char *alg8[] = {
/* columns rows colors chars-per-pixel */
"32 42 16",
"c 0x000000",
". 0x2D3B4D",
"X 0x36475C",
"o 0x3D5068",
"O 0x435873",
"+ 0x495F7C",
"@ 0x4E6685",
"# 0x536C8D",
"$ 0x577294",
"% 0x5B779B",
"& 0x5F7CA1",
"* 0x6281A7",
"= 0x6685AD",
" 0x6989B3",
"; 0x6C8EB8",
": 0x7092BE",
/* pixels */
"cccc.::::::::::::::::::::::.cccc",
"cccc@::::::::::::::::::::::#cccc",
"cccc=::::::::::::::::::::::*cccc",
"cc.#::::::::::::::::::::::::#ccc",
"X=::::::::::::::::::::::::::::*o",
"=::::::::::=========-::::::::::=",
":::::::::@ccccccccccc.+:::::::::",
"::::::::*cccccccccccccc&::::::::",
"::::::::@cccccccccccccc@::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::@cccccccccccccc#::::::::",
"::::::::&cccccccccccccc=::::::::",
":::::::::%XccccccccccX$:::::::::",
"*::::::::::::::::::::::::::::::*",
".&::::::::::::::::::::::::::::&.",
"cc.*::::::::::::::::::::::::*ccc",
"ccc@::::::::::::::::::::::::@ccc",
"cX$::::::::::::::::::::::::::$.c",
"@::::::::::::::::::::::::::::::@",
";:::::::::&$$$$$$$$$$&:::::::::;",
"::::::::;.cccccccccccc.;::::::::",
"::::::::&cccccccccccccc$::::::::",
"::::::::+cccccccccccccc+::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::$cccccccccccccc%::::::::",
"::::::::-cccccccccccccc-::::::::",
";::::::::-%OOOOOOOOOO$;:::::::::",
"%::::::::::::::::::::::::::::::#",
"co$;::::::::::::::::::::::::;%Oc",
"ccc.;:::::::::::::::::::::::.ccc",
"cccc%::::::::::::::::::::::%cccc",
"ccccO::::::::::::::::::::::occcc"
};


/* XPM */
static char *alg9[] = {
/* columns rows colors chars-per-pixel */
"32 42 16",
"c 0x000000",
". 0x2D3B4D",
"X 0x36475C",
"o 0x3D5068",
"O 0x435873",
"+ 0x495F7C",
"@ 0x4E6685",
"# 0x536C8D",
"$ 0x577294",
"% 0x5B779B",
"& 0x5F7CA1",
"* 0x6281A7",
"= 0x6685AD",
"- 0x6989B3",
"; 0x6C8EB8",
": 0x7092BE",
/* pixels */
"ccccc%::::::::::::::::::::#ccccc",
"cccco::::::::::::::::::::::Occcc",
"cccc%::::::::::::::::::::::%cccc",
"ccc.;::::::::::::::::::::::;cccc",
"cX#-::::::::::::::::::::::::=@.c",
"@::::::::::::::::::::::::::::::@",
";::::::::;$OOOOOOOOOO$-::::::::;",
"::::::::;cccccccccccccc=::::::::",
"::::::::%cccccccccccccc#::::::::",
"::::::::+ccccccccccccccO::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::OccccccccccccccO::::::::",
"::::::::@cccccccccccccc#::::::::",
"::::::::&cccccccccccccc*::::::::",
":::::::::#.cccccccccc.#:::::::::",
"*:::::::::::::::::::::::::::::::",
".%;:::::::::::::::::::::::::::::",
"cccO::::::::::::::::::::::::::::",
"cccc&:::::::::::::::::::::::::::",
"cccc@:::::::::::::::::::::::::::",
"ccccc-::::::::::::::::::::::::::",
"ccccccOOOOOOOOOOOOOOO#-:::::::::",
"ccccccccccccccccccccccc=::::::::",
"ccccccccccccccccccccccc#::::::::",
"cccccccccccccccccccccccO::::::::",
"cccccccccccccccccccccccO::::::::",
"cccccccccccccccccccccccO::::::::",
"cccccccccccccccccccccccO::::::::",
"cccccccccccccccccccccccO::::::::",
"cccccccccccccccccccccccO::::::::",
"ccccccccccccccccccccccc%::::::::",
"ccccccccccccccccccccccc;::::::::",
"co$$$$$$$$$$$$$$$$$$$%;:::::::::",
"$::::::::::::::::::::::::::::::@",
";:::::::::::::::::::::::::::;$oc",
":::::::::::::::::::::::::::;.ccc",
":::::::::::::::::::::::::::%cccc",
"-::::::::::::::::::::::::::occcc",
"o-::::::::::::::::::::::::%ccccc"
};

/* XPM */
static char * bar[] = {
"32 42 20",
"!	0x000000",
"#	0x00002E",
"$	0x243ECC",
"%	0x3F48CC",
"&	0x3F3352",
"'	0x001073",
"(	0x3648CC",
")	0x2D1D00",
"*	0x0E28AF",
"+	0x3F48AF",
",	0x241000",
"-	0x1933CC",
".	0x3F3E73",
"0	0x0E0000",
"1	0x000052",
"2	0x2D48CC",
"3	0x36282E",
"4	0x001D91",
"5	0x3F4891",
"6	0x190000",
"!!!!!!!!!!!!!!!!!!#$%%%%%&!!!!!!",
"!!!!!!!!!!!!!!!!!!'(%%%%%)!!!!!!",
"!!!!!!!!!!!!!!!!!!*%%%%%+,!!!!!!",
"!!!!!!!!!!!!!!!!!!-%%%%%.0!!!!!!",
"!!!!!!!!!!!!!!!!!12%%%%%3!!!!!!!",
"!!!!!!!!!!!!!!!!!4%%%%%%)!!!!!!!",
"!!!!!!!!!!!!!!!!!-%%%%%56!!!!!!!",
"!!!!!!!!!!!!!!!!#$%%%%%&!!!!!!!!",
"!!!!!!!!!!!!!!!!'(%%%%%)!!!!!!!!",
"!!!!!!!!!!!!!!!!*%%%%%+,!!!!!!!!",
"!!!!!!!!!!!!!!!!-%%%%%.0!!!!!!!!",
"!!!!!!!!!!!!!!!12%%%%%3!!!!!!!!!",
"!!!!!!!!!!!!!!!4%%%%%%)!!!!!!!!!",
"!!!!!!!!!!!!!!!-%%%%%56!!!!!!!!!",
"!!!!!!!!!!!!!!#$%%%%%&!!!!!!!!!!",
"!!!!!!!!!!!!!!'(%%%%%)!!!!!!!!!!",
"!!!!!!!!!!!!!!*%%%%%+,!!!!!!!!!!",
"!!!!!!!!!!!!!!-%%%%%.0!!!!!!!!!!",
"!!!!!!!!!!!!!'(%%%%%)!!!!!!!!!!!",
"!!!!!!!!!!!!!*%%%%%+,!!!!!!!!!!!",
"!!!!!!!!!!!!#$%%%%%.0!!!!!!!!!!!",
"!!!!!!!!!!!!12%%%%%3!!!!!!!!!!!!",
"!!!!!!!!!!!!4%%%%%+,!!!!!!!!!!!!",
"!!!!!!!!!!!!-%%%%%56!!!!!!!!!!!!",
"!!!!!!!!!!!#$%%%%%&!!!!!!!!!!!!!",
"!!!!!!!!!!!'(%%%%%)!!!!!!!!!!!!!",
"!!!!!!!!!!!*%%%%%+,!!!!!!!!!!!!!",
"!!!!!!!!!!!-%%%%%.0!!!!!!!!!!!!!",
"!!!!!!!!!!12%%%%%3!!!!!!!!!!!!!!",
"!!!!!!!!!!4%%%%%%)!!!!!!!!!!!!!!",
"!!!!!!!!!!-%%%%%56!!!!!!!!!!!!!!",
"!!!!!!!!!#$%%%%%&!!!!!!!!!!!!!!!",
"!!!!!!!!!'(%%%%%)!!!!!!!!!!!!!!!",
"!!!!!!!!!*%%%%%+,!!!!!!!!!!!!!!!",
"!!!!!!!!!-%%%%%.0!!!!!!!!!!!!!!!",
"!!!!!!!!12%%%%%3!!!!!!!!!!!!!!!!",
"!!!!!!!!4%%%%%%)!!!!!!!!!!!!!!!!",
"!!!!!!!!-%%%%%56!!!!!!!!!!!!!!!!",
"!!!!!!!#$%%%%%&!!!!!!!!!!!!!!!!!",
"!!!!!!!'(%%%%%)!!!!!!!!!!!!!!!!!",
"!!!!!!!*%%%%%+,!!!!!!!!!!!!!!!!!",
"!!!!!!!-%%%%%.0!!!!!!!!!!!!!!!!!"};
