/* XPM */
static char *bad[] = {
/* columns rows colors chars-per-pixel */
"43 30 7 1",
"  c #1E1D2E",
". c #44394E",
"X c #7D6293",
"o c #B0A0CA",
"O c #F5C8E5",
"+ c #DDF5E8",
"@ c None",
/* pixels */
"@@@@@@@@@@@@@XXXXX.@@@@@.XXXXX@@@@@@@@@@@@@",
"@@@@@@@@@@@@XXO+++O.@@@.O+++OXX@@@@@@@@@@@@",
"@@@.....O@@@XXO+++O.. ..O+++OXX@@@O.....@@@",
"@@@.     O   +X+++X.. ..X+++X+   O     .@@@",
"@@@.      O...+oooo.. ..oooo+...O      .@@@",
"@@          .. O++.X. .X.++O ..          @@",
"@ .. XXXXX.X.. XXX.XX XX.XXX ..X.XXXXX .. @",
".X...   ..XX.. XXX.XX.XX.XXX ..XX..   ...X.",
".X..... XXXX..XXXX.XX.XX.XXXX..XXXX .....X.",
".X.... OOOOO  O++O.OO.OO.O++O  OOOOO ....X.",
".OOO .oooX.   ooooXoo ooXoooo   .Xooo. OOO.",
".oooOoooo.    ooooXoo ooXoooo    .ooooOooo.",
".oooOoooOooOOOooooXoo ooXooooOOOooOoooOooo.",
".oXooOooOXXooooXXoXoo ooXoXXooooXXOooOooXo.",
".ooXooO++XXOOOooooXoOOOoXooooOOOXX++OooXoo.",
".oo.oooo+XX...ooooXoOOOoXoooo...XX+oooo.oo.",
".oo.ooooo++...oXXoXoOOOoXoXXo...++ooooo.oo.",
".ooXooooooo  .ooooXo+O+oXoooo.  oooooooXoo.",
".OOXooooooo  .ooooXO+++OXoooo.  oooooooXOO.",
"XOOXooooooo. .oO++ O+++O ++Oo. .oooooooXOOX",
"X+Oo+++OOOOO .oO++ X+X+X ++Oo. OOOOO+++oO+X",
"Xo+o+++OOOOO .OO++X XXX X++OO. OOOOO+++o+oX",
"Xoo+XXXX.XX ... X.OO...OO.X ... XX.XXXX+ooX",
"XXXoo..XX. OOO .X.OO...OO.X. OOO .XX..ooXXX",
"@@@XX  .XX ooo XX.X.+++.X.XX ooo XX.  XX@@@",
"@@@@@  @.X.ooo.XoXOX+++XOXoX.ooo.X.@  @@@@@",
"@@@@@  @@..ooo.oXOOXXXXXOOXo.ooo..@@  @@@@@",
"@@@@@@@@@@.O++...XX@@@@@XX...++O.@@@@@@@@@@",
"@@@@@@@@@@@.++.@@@@@@@@@@@@@.++.@@@@@@@@@@@",
"@@@@@@@@@@@@...@@@@@@@@@@@@@...@@@@@@@@@@@@"
};
