/*
life = 8
quando life >4 green
quando life <= 4 ou >2 yellow
quando life <= 2 red
 */

/* XPM */
static char *lbarg[] = {
/* columns rows colors chars-per-pixel */
"41 50 1",
"c 0x22B14C",
/* pixels */
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc"
};


/* XPM */
static char *lbary[] = {
/* columns rows colors chars-per-pixel */
"41 50 1",
"c 0xFFF200",
/* pixels */
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc"
};


/* XPM */
static char *lbarr[] = {
/* columns rows colors chars-per-pixel */
"41 50 1",
"c 0xED1C24",
/* pixels */
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc"
};


/* XPM */
static char *lbarb[] = {
/* columns rows colors chars-per-pixel */
"41 50 1",
"c 0x000000",
/* pixels */
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccccccccccccccccccccccc"
};


/* XPM */
static char * hp[] = {
"22 14 5",
"!	0xFFFFFF",
"#	0x22B14C",
"$	0xE1E1E1",
"%	0xD0D0D0",
"&	0xF8F8F8",
"!!!#####!!!!!!!!!!!!$#",
"!!!#####!!!!!!!!!!!!!$",
"!!!#####!!!!!!$###$!!!",
"!!!#####!!!!!!#####!!!",
"!!!#####!!!!!!#####!!!",
"!!!$###%!!!!!!$###$!!!",
"!!!!!!!!!!!!!!!!!!!!!!",
"!!!!!!!!!!!!!!!!!!!!!#",
"!!!!%%%!!!!!!!&%%%%%##",
"!!!#####!!!!!!########",
"!!!#####!!!!!!########",
"!!!#####!!!!!!########",
"!!!#####!!!!!!########",
"!!!#####!!!!!!########"};
