/* XPM */
static char *left_right_frame[] = {
/* columns rows colors chars-per-pixel */
"5 120 1",
"% 0xFF0000",
/* pixels */
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%"
};


/* XPM */
static char *upper_lower_frame[] = {
/* columns rows colors chars-per-pixel */
"1024 4 1",
"% 0xFF0000",
/* pixels */
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
};


/* XPM */
static char *levelS[] = {
/* columns rows colors chars-per-pixel */
"198 42 18",
"c 0x000000",
". 0x191D53",
"X 0x3F3352",
"o 0x1E2363",
"O 0x222770",
"+ 0x262B7B",
"@ 0x001D91",
"# 0x292F85",
"$ 0x2C328F",
"% 0x2E3597",
"& 0x31389F",
"* 0x333AA6",
"= 0x353DAD",
"- 0x373FB4",
"; 0x3941BA",
": 0x3B43C0",
"> 0x3D46C6",
", 0x3F48CC",
/* pixels */

//-9 -9 -17 -63
"O>,,,,>%ccccccccccccccccccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,;OccO>,,,,>%cccccccccccccccc%,,,,,:Occccccc*,,,,,,,,,,,,,,,,,,,,,,,,;OccO>,,,,>%cccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"-,,,,,,,OcccccccccccccccccccccccccccccO,,,,,,,,,,,,,,,,,,,,,,,,,,;cc-,,,,,,,Occcccccccccccco,,,,,,,:ccccccO,,,,,,,,,,,,,,,,,,,,,,,,,,;cc-,,,,,,,Occccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,,cc,,,,,,,,+cccccccccccccc+,,,,,,,,cccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+cccccccccccccccccccccccccccco,,,,,,,,,,,,,,,,,,,,,,,,,,,,cc,,,,,,,,+cccccccccccccc+,,,,,,,,ccccco,,,,,,,,,,,,,,,,,,,,,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+cccccccccccccccccccccccccc$-,,,,,,,,,,,,,,,,,,,,,,,,,,,,:cc,,,,,,,,+cccccccccccccc+,,,,,,,,ccc$-,,,,,,,,,,,,,,,,,,,,,,,,,,,,:cc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#cc,,,,,,,,+cccccccccccccc+,,,,,,,,cc*,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#cc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,;%+++++++++++++++++++occc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,;%+++++++++++++++++++occc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,;ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,;ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,&ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,%ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,%ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,=ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,=ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,&occccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,&occccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-Occ,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-Occ,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-cc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-cc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&cc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&cc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,,-&&&&&&&&&&&&&&&&&&&$ccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,-&&&&&&&&&&&&&&&&&&&$ccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,>.cccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,>.cccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,=ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,=ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,$ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,$ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&cccccccccccccc%,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,>.ccccccccccccc:,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc>,,,,,,,,:&Occcccccco$>,,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc*,,,,,,,,,,,$cccccc$,,,,,,,,,,,&cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,#cccccccccccccccccccccccccc+*,,,,,,,,,,cccccc,,,,,,,,,,-#ccc,,,,,,,,#ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,&ccccccccccccccccccccccccc,,,,,,,,&cccccccccccccccccccccccccccc.>,,,,,,,,+cccc+,,,,,,,,,.ccccc,,,,,,,,&ccccccccccccccccccccccccc,,,,,,,,&ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,>.cccccccccccccccccccccccc,,,,,,,,>.cccccccccccccccccccccccccccc*,,,,,,,,-.cc.-,,,,,,,,*cccccc,,,,,,,,>.cccccccccccccccccccccccc,,,,,,,,>.cccccccccccccccccccccccccccccccccccccccccccccccccccc",
">,,,,,,,,>*&&&&&&&&&&&&&&&&&&%Occc>,,,,,,,,>*&&&&&&&&&&&&&&&&&&%Occccccc#,,,,,,,,,>==>,,,,,,,,,+cccccc>,,,,,,,,>*&&&&&&&&&&&&&&&&&&%Occc>,,,,,,,,>*&&&&&&&&&&&&&&&&&&%Occccccccccccccccccccccccccccccc",
"%,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,$cc%,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,$ccccccc:,,,,,,,,,,,,,,,,,,,,;ccccccc%,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,$cc%,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,$cccccccccccccccccccccccccccccc",
"cO%>,,,,,,,,,,,,,,,,,,,,,,,,,,,;cccO%>,,,,,,,,,,,,,,,,,,,,,,,,,,,;cccccccc+*,,,,,,,,,,,,,,,>*OcccccccccO%>,,,,,,,,,,,,,,,,,,,,,,,,,,,;cccO%>,,,,,,,,,,,,,,,,,,,,,,,,,,,;cccccccccccccccccccccccccccccc",
"ccc.>,,,,,,,,,,,,,,,,,,,,,,,,,,;ccccc.>,,,,,,,,,,,,,,,,,,,,,,,,,,;ccccccccccO,,,,,,,,,,,,,,+ccccccccccccc.>,,,,,,,,,,,,,,,,,,,,,,,,,,;ccccc.>,,,,,,,,,,,,,,,,,,,,,,,,,,;cccccccccccccccccccccccccccccc",
"cccc*,,,,,,,,,,,,,,,,,,,,,,,,,,;cccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,;ccccccccccc,,,,,,,,,,,,,>ccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,;cccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,;cccccccccccccccccccccccccccccc",
"cccc+,,,,,,,,,,,,,,,,,,,,,,,,,,-cccccc+,,,,,,,,,,,,,,,,,,,,,,,,,,-ccccccccccc=,,,,,,,,,,,,*ccccccccccccccc+,,,,,,,,,,,,,,,,,,,,,,,,,,-cccccc+,,,,,,,,,,,,,,,,,,,,,,,,,,-cccccccccccccccccccccccccccccc",
"ccccc*,,,,,,,,,,,,,,,,,,,,,,,,>occccccc*,,,,,,,,,,,,,,,,,,,,,,,,>occccccccccc.;,,,,,,,,,,;.cccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,>occccccc*,,,,,,,,,,,,,,,,,,,,,,,,>occcccccccccccccccccccccccccccc"
};


/* XPM */
static char *livesS[] = {
/* columns rows colors chars-per-pixel */
"172 42 18",
"c 0x000000",
". 0x191D53",
"X 0x3F3352",
"o 0x1E2363",
"O 0x222770",
"+ 0x262B7B",
"@ 0x001D91",
"# 0x292F85",
"$ 0x2C328F",
"% 0x2E3597",
"& 0x31389F",
"* 0x333AA6",
"= 0x353DAD",
"- 0x373FB4",
"; 0x3941BA",
": 0x3B43C0",
"> 0x3D46C6",
", 0x3F48CC",
/* pixels */
//-9 -9 -15
"O>,,,,>%ccccccccccccccccccccccccccO>,,,,,&ccO>,,,,>%cccccccccccccccc%,,,,,:Occccccc*,,,,,,,,,,,,,,,,,,,,,,,,;Occccccc*,,,,,,,,,,,,,,,,,,,,,,,,:Occcccccccccccccccccccccccccc",
"-,,,,,,,Occccccccccccccccccccccccc:,,,,,,,#c-,,,,,,,Occcccccccccccco,,,,,,,:ccccccO,,,,,,,,,,,,,,,,,,,,,,,,,,;ccccccO,,,,,,,,,,,,,,,,,,,,,,,,,,:cccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,,cccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,,cccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,ccccco,,,,,,,,,,,,,,,,,,,,,,,,,,,,ccccc.,,,,,,,,,,,,,,,,,,,,,,,,,,,,cccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,ccc$-,,,,,,,,,,,,,,,,,,,,,,,,,,,,:cccO&>,,,,,,,,,,,,,,,,,,,,,,,,,,,>cccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc*,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#cc$,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&cccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,;%+++++++++++++++++++occc,,,,,,,,,>*&&&&&&&&&&&&&&&&&&&Occccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,;ccccccccccccccccccccccccc,,,,,,,,>.cccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,&ccccccccccccccccccccccccc,,,,,,,,*ccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,%ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,=ccccccccccccccccccccccccc,,,,,,,,$ccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,&occccccccccccccccccccccc,,,,,,,,=ccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-Occ,,,,,,,,,%.ccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-cc-,,,,,,,,,,,,,,,,,,,,,,,,,&ccccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc.*>,,,,,,,,,,,,,,,,,,,,,,,,+cccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;ccccc+,,,,,,,,,,,,,,,,,,,,,,,*cccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cccccc=,,,,,,,,,,,,,,,,,,,,,,>.ccccccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&cccccc$,,,,,,,,,,,,,,,,,,,,,,,>&Occccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,-&&&&&&&&&&&&&&&&&&&$cccccccc:,,,,,,,,,,,,,,,,,,,,,,,,,*cccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,>.cccccccccccccccccccccccccccccc+++++++++++++++%:,,,,,,,,>cccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,=cccccccccccccccccccccccccccccccccccccccccccccccc;,,,,,,,,cccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,$cccccccccccccccccccccccccccccccccccccccccccccccc%,,,,,,,,cccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccc+,,,,,,,,cccccccccccccccccccccccccccc",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,&cccccccccccccc%,,,,,,,,cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccc+,,,,,,,,cccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,>.ccccccccccccc:,,,,,,,,cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccc+,,,,,,,,cccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c>,,,,,,,,:&Occcccccco$>,,,,,,,,,cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccc+,,,,,,,,cccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c*,,,,,,,,,,,$cccccc$,,,,,,,,,,,&cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccc+,,,,,,,,cccccccccccccccc@,,,,,,,,,,X",
",,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&cc+*,,,,,,,,,,cccccc,,,,,,,,,,-#ccc,,,,,,,,#cccccccccccccccccccccccccccccccccccccccccccccccc+,,,,,,,,cccccccccccccccccccccccccccc",
",,,,,,,,&ccccccccccccccccccccccccc,,,,,,,,&cccc.>,,,,,,,,+cccc+,,,,,,,,,.ccccc,,,,,,,,&cccccccccccccccccccccccccccccccccccccccccccccccc*,,,,,,,,cccccccccccccccccccccccccccc",
",,,,,,,,>.cccccccccccccccccccccccc,,,,,,,,&ccccc*,,,,,,,,-.cc.-,,,,,,,,*cccccc,,,,,,,,>.cccccccccccccccccccccccccccccccccccccccccccccc.>,,,,,,,,cccccccccccccccc@,,,,,,,,,,X",
">,,,,,,,,>*&&&&&&&&&&&&&&&&&&%Occc,,,,,,,,&ccccc#,,,,,,,,,>==>,,,,,,,,,+cccccc>,,,,,,,,>*&&&&&&&&&&&&&&&&&&%OccccO&&&&&&&&&&&&&&&&&&&*>,,,,,,,,,cccccccccccccccc@,,,,,,,,,,X",
"%,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,$cc,,,,,,,,&cccccc:,,,,,,,,,,,,,,,,,,,,;ccccccc%,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,$cc&,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,$cccccccccccccccc@,,,,,,,,,,X",
"cO%>,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,&ccccccc+*,,,,,,,,,,,,,,,>*OcccccccccO%>,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc>,,,,,,,,,,,,,,,,,,,,,,,,,,,>&Occccccccccccccccc@,,,,,,,,,,X",
"ccc.>,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,&cccccccccO,,,,,,,,,,,,,,+ccccccccccccc.>,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,,,,,,,,,,,,,,,,,,,,>.ccccccccccccccccccccccccccccccc",
"cccc*,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,&cccccccccc,,,,,,,,,,,,,>ccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,,,,,,,,,,,,,,,,,,,,*cccccccccccccccccccccccccccccccc",
"cccc+,,,,,,,,,,,,,,,,,,,,,,,,,,-cc>,,,,,,,Occcccccccc=,,,,,,,,,,,,*ccccccccccccccc+,,,,,,,,,,,,,,,,,,,,,,,,,,-cc:,,,,,,,,,,,,,,,,,,,,,,,,,,Occcccccccccccccccccccccccccccccc",
"ccccc*,,,,,,,,,,,,,,,,,,,,,,,,>occO:,,,,,*ccccccccccc.;,,,,,,,,,,;.cccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,>occO:,,,,,,,,,,,,,,,,,,,,,,,,*ccccccccccccccccccccccccccccccccc"
};

/* XPM */
static char *scoreS[] = {
/* columns rows colors chars-per-pixel */
"89 24 11",
"c 0x000000",
". 0x191D53",
"X 0x222770",
"o 0x262B7B",
"O 0x292F85",
"+ 0x2E3597",
"@ 0x333AA6",
"# 0x373FB4",
"$ 0x3941BA",
"% 0x3B43C0",
"& 0x3F48CC",
/* pixels */
//-16 -20 -3 -3
"ccccccccccccccccccccccccccccoOOOOOocccccccccccccccccccccccccccccccccccccccccccccccoOOOOOo",
"cco&&&&&&&&&&&&&&ccco&&&&&&&&&&&&&&ccccO&&&&&&&&&&Occc&&&&&&&&&&&&&&XcccccO&&&&&&&&&&&&&&",
"cc%&&&&&&&&&&&&&&ccc%&&&&&&&&&&&&&&cccc%&&&&&&&&&&%ccc&&&&&&&&&&&&&&$ccccc%&&&&&&&&&&&&&&",
"o$&&&&&&&&&&&&&&&cX$&&&&&&&&&&&&&&&cco$&&&&&&&&&&&&%oc&&&&&&&&&&&&&&&#Xc+&&&&&&&&&&&&&&&&",
"&&&&&%##########Oc&&&&&%##########@cc&&&&&$####$&&&&&c&&&&&%#####%&&&&&c&&&&&%##########@",
"&&&&%ccccccccccccc&&&&%cccccccccccccc&&&&%cccccc$&&&&c&&&&&ccccccc%&&&&c&&&&$cccccccccccc",
"&&&&#ccccccccccccc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&#ccccccc#&&&&c&&&&#cccccccccccc",
"&&&&#ccccccccccccc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&#ccccccc#&&&&c&&&&#cccccccccccc",
"&&&&#ccccccccccccc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&#ccccccc#&&&&c&&&&#cccccccccccc",
"&&&&#ccccccccccccc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&#ccccccc#&&&&c&&&&&Xccccccccccc",
"&&&&&Xcccccccccccc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&&XcccccX&&&&&c&&&&&&&&&&&&&&&&&",
"$&&&&&&&&&&&&&occc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&&&&&&&&&&&&&%c&&&&&&&&&&&&&&&&&",
"c.&&&&&&&&&&&&$ccc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&&&&&&&&&&&&Occ&&&&&&&&&&&&&&&&&",
"cc@&&&&&&&&&&&&$Xc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&&&&&&&&&&&&&oc&&&&&&##########@",
"ccc@#######%&&&&&c&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&&%#####%&&&&&c&&&&&cccccccccccc",
"cccccccccccc%&&&&c&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&%ccccccc%&&&&c&&&&#cccccccccccc",
"cccccccccccc#&&&&c&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&#ccccccc#&&&&c&&&&#cccccccccccc",
"cccccccccccc#&&&&c&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&#ccccccc#&&&&c&&&&#cccccccccccc",
"cccccccccccc#&&&&c&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&#ccccccc#&&&&c&&&&#cccccccccccc",
"cccccccccccc%&&&&c&&&&%cccccccccccccc&&&&$cccccc$&&&&c&&&&#ccccccc#&&&&c&&&&&cccccccccccc",
"O##########%&&&&&c&&&&&%##########@cc&&&&&$####$&&&&&c&&&&#ccccccc#&&&&c&&&&&%##########@",
"&&&&&&&&&&&&&&&$oco%&&&&&&&&&&&&&&&cco%&&&&&&&&&&&&$oc&&&&#ccccccc#&&&&co%&&&&&&&&&&&&&&&",
"&&&&&&&&&&&&&&%ccccc$&&&&&&&&&&&&&&cccc%&&&&&&&&&&%ccc&&&&#ccccccc#&&&&ccc$&&&&&&&&&&&&&&",
"&&&&&&&&&&&&&&occccco&&&&&&&&&&&&&&ccccO&&&&&&&&&&Occc&&&&OcccccccO&&&&ccco&&&&&&&&&&&&&&"
};


/* XPM */
static char *dolarS[] = {
/* columns rows colors chars-per-pixel */
"22 42 20",
"c black",
". 0x080000",
"X 0x0E0000",
"o 0x000011",
"O 0x00001F",
"+ 0x142800",
"@ 0x00282B",
"# 0x184700",
"$ 0x1D6411",
"% 0x227F1F",
"& 0x004736",
"* 0x086442",
"= 0x0E7F4C",
"- 0x22982B",
"; 0x22B136",
": 0x14984C",
"> 0x18B14C",
", 0x1DB14C",
"< 0x22B142",
"1 0x22B14C",
/* pixels */
//-9 -9 -10 -6
"cccccccc&11#cccccccccc",
"cccccccc=11-.ccccccccc",
"ccccO>111111;Xcccccccc",
"cc@,111111111111$ccccc",
"c&111-.cO>1111111<+ccc",
"O>11#cccco:1111111<+cc",
"*11$ccccccO>1111111;Xc",
":1;Xccccccc=11111111$c",
">1-.ccccccc*11111111%c",
">1;Xccccccc*11111111%c",
">11$ccccccc*11111111%c",
">11<+cccccc*11111111%c",
">111;Xccccc*11111111%c",
">11111#cccc*11111111$c",
">111111<+ccO>111111<+c",
">11111111<+c@,11111#cc",
":11111111111#co:1$cccc",
"*1111111111111#ccccccc",
"O>11111111111111$ccccc",
"c&111111111111111-.ccc",
"cc&111111111111111;Xcc",
"ccco:11111111111111%cc",
"cccccO>111111111111<+c",
"cccccccO>11111111111$c",
"cc@,1-.ccO>111111111%c",
"o:11111<+ccO>1111111-.",
"*1111111;Xccc@,11111-.",
":11111111#ccccc=1111-.",
">11111111#cccccc*111-.",
">11111111#cccccco:11-.",
">11111111#ccccccc*11-.",
">11111111#ccccccc*11-.",
">11111111#ccccccc=11-.",
":11111111$ccccccO>11%c",
"*111111111#ccccc*111$c",
"c=1111111111#cO>111-.c",
"cc=111111111111111-.cc",
"ccc&1111111111111#cccc",
"cccccco:111111%ccccccc",
"cccccccco:11#ccccccccc",
"ccccccccc=1;Xccccccccc",
"ccccccccc&1%cccccccccc"
};
