/* XPM */
static char *left_right_frame[] = {
/* columns rows colors chars-per-pixel */
"5 120 1",
"% 0xFF0000",
/* pixels */
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%",
"%%%%%"
};


/* XPM */
static char *upper_lower_frame[] = {
/* columns rows colors chars-per-pixel */
"512 4 1",
"% 0xFF0000",
/* pixels */
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%",
"%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%"
};


/* XPM */
static char *level[] = {
/* columns rows colors chars-per-pixel */
"278 60 18",
"c 0x000000",
". 0x191D53",
"X 0x3F3352",
"o 0x1E2363",
"O 0x222770",
"+ 0x262B7B",
"@ 0x001D91",
"# 0x292F85",
"$ 0x2C328F",
"% 0x2E3597",
"& 0x31389F",
"* 0x333AA6",
"= 0x353DAD",
"- 0x373FB4",
"; 0x3941BA",
": 0x3B43C0",
"> 0x3D46C6",
", 0x3F48CC",
/* pixels */
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccO>,,,,>%ccccccccccccccccccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,;OccO>,,,,>%cccccccccccccccc%,,,,,:Occccccc*,,,,,,,,,,,,,,,,,,,,,,,,;OccO>,,,,>%ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc-,,,,,,,OcccccccccccccccccccccccccccccO,,,,,,,,,,,,,,,,,,,,,,,,,,;cc-,,,,,,,Occcccccccccccco,,,,,,,:ccccccO,,,,,,,,,,,,,,,,,,,,,,,,,,;cc-,,,,,,,Occcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,,cc,,,,,,,,+cccccccccccccc+,,,,,,,,cccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,,cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+cccccccccccccccccccccccccccco,,,,,,,,,,,,,,,,,,,,,,,,,,,,cc,,,,,,,,+cccccccccccccc+,,,,,,,,ccccco,,,,,,,,,,,,,,,,,,,,,,,,,,,,cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+cccccccccccccccccccccccccc$-,,,,,,,,,,,,,,,,,,,,,,,,,,,,:cc,,,,,,,,+cccccccccccccc+,,,,,,,,ccc$-,,,,,,,,,,,,,,,,,,,,,,,,,,,,:cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#cc,,,,,,,,+cccccccccccccc+,,,,,,,,cc*,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#cc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,;%+++++++++++++++++++occc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,;%+++++++++++++++++++occc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,;ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,;ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,&ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,%ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,%ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,=ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,=ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,&occccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,&occccccccccccccccccccccc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-Occ,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-Occ,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-cc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&cc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,,,-&&&&&&&&&&&&&&&&&&&$ccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,-&&&&&&&&&&&&&&&&&&&$ccc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,>.cccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,>.cccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,=ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,=ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,$ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,$ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&cccccccccccccc%,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,>.ccccccccccccc:,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc>,,,,,,,,:&Occcccccco$>,,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc*,,,,,,,,,,,$cccccc$,,,,,,,,,,,&cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,#cccccccccccccccccccccccccc+*,,,,,,,,,,cccccc,,,,,,,,,,-#ccc,,,,,,,,#ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,&ccccccccccccccccccccccccc,,,,,,,,&cccccccccccccccccccccccccccc.>,,,,,,,,+cccc+,,,,,,,,,.ccccc,,,,,,,,&ccccccccccccccccccccccccc,,,,,,,,&ccccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc,,,,,,,,>.cccccccccccccccccccccccc,,,,,,,,>.cccccccccccccccccccccccccccc*,,,,,,,,-.cc.-,,,,,,,,*cccccc,,,,,,,,>.cccccccccccccccccccccccc,,,,,,,,>.ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc>,,,,,,,,>*&&&&&&&&&&&&&&&&&&%Occc>,,,,,,,,>*&&&&&&&&&&&&&&&&&&%Occccccc#,,,,,,,,,>==>,,,,,,,,,+cccccc>,,,,,,,,>*&&&&&&&&&&&&&&&&&&%Occc>,,,,,,,,>*&&&&&&&&&&&&&&&&&&%Occcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccc%,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,$cc%,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,$ccccccc:,,,,,,,,,,,,,,,,,,,,;ccccccc%,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,$cc%,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,$ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccO%>,,,,,,,,,,,,,,,,,,,,,,,,,,,;cccO%>,,,,,,,,,,,,,,,,,,,,,,,,,,,;cccccccc+*,,,,,,,,,,,,,,,>*OcccccccccO%>,,,,,,,,,,,,,,,,,,,,,,,,,,,;cccO%>,,,,,,,,,,,,,,,,,,,,,,,,,,,;ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccc.>,,,,,,,,,,,,,,,,,,,,,,,,,,;ccccc.>,,,,,,,,,,,,,,,,,,,,,,,,,,;ccccccccccO,,,,,,,,,,,,,,+ccccccccccccc.>,,,,,,,,,,,,,,,,,,,,,,,,,,;ccccc.>,,,,,,,,,,,,,,,,,,,,,,,,,,;ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,;cccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,;ccccccccccc,,,,,,,,,,,,,>ccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,;cccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,;ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccccc+,,,,,,,,,,,,,,,,,,,,,,,,,,-cccccc+,,,,,,,,,,,,,,,,,,,,,,,,,,-ccccccccccc=,,,,,,,,,,,,*ccccccccccccccc+,,,,,,,,,,,,,,,,,,,,,,,,,,-cccccc+,,,,,,,,,,,,,,,,,,,,,,,,,,-ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,>occccccc*,,,,,,,,,,,,,,,,,,,,,,,,>occccccccccc.;,,,,,,,,,,;.cccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,>occccccc*,,,,,,,,,,,,,,,,,,,,,,,,>occccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
};


/* XPM */
static char *livesS[] = {
/* columns rows colors chars-per-pixel */
"268 60 18",
"c 0x000000",
". 0x191D53",
"X 0x3F3352",
"o 0x1E2363",
"O 0x222770",
"+ 0x262B7B",
"@ 0x001D91",
"# 0x292F85",
"$ 0x2C328F",
"% 0x2E3597",
"& 0x31389F",
"* 0x333AA6",
"= 0x353DAD",
"- 0x373FB4",
"; 0x3941BA",
": 0x3B43C0",
"> 0x3D46C6",
", 0x3F48CC",
/* pixels */
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccO>,,,,>%ccccccccccccccccccccccccccO>,,,,,&ccO>,,,,>%cccccccccccccccc%,,,,,:Occccccc*,,,,,,,,,,,,,,,,,,,,,,,,;Occccccc*,,,,,,,,,,,,,,,,,,,,,,,,:Occccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc-,,,,,,,Occccccccccccccccccccccccc:,,,,,,,#c-,,,,,,,Occcccccccccccco,,,,,,,:ccccccO,,,,,,,,,,,,,,,,,,,,,,,,,,;ccccccO,,,,,,,,,,,,,,,,,,,,,,,,,,:ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,,cccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,,ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,ccccco,,,,,,,,,,,,,,,,,,,,,,,,,,,,ccccc.,,,,,,,,,,,,,,,,,,,,,,,,,,,,ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,ccc$-,,,,,,,,,,,,,,,,,,,,,,,,,,,,:cccO&>,,,,,,,,,,,,,,,,,,,,,,,,,,,>ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc*,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,#cc$,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,;%+++++++++++++++++++occc,,,,,,,,,>*&&&&&&&&&&&&&&&&&&&Occcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,;ccccccccccccccccccccccccc,,,,,,,,>.ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,&ccccccccccccccccccccccccc,,,,,,,,*cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,%ccccccccccccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,=ccccccccccccccccccccccccc,,,,,,,,$ccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,&occccccccccccccccccccccc,,,,,,,,=ccccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-Occ,,,,,,,,,%.ccccccccccccccccccccccccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,-cc-,,,,,,,,,,,,,,,,,,,,,,,,,&cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc.*>,,,,,,,,,,,,,,,,,,,,,,,,+ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;ccccc+,,,,,,,,,,,,,,,,,,,,,,,*ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,;cccccc=,,,,,,,,,,,,,,,,,,,,,,>.cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,&cccccc$,,,,,,,,,,,,,,,,,,,,,,,>&Occcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,,,-&&&&&&&&&&&&&&&&&&&$cccccccc:,,,,,,,,,,,,,,,,,,,,,,,,,*ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,>.cccccccccccccccccccccccccccccc+++++++++++++++%:,,,,,,,,>ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,=cccccccccccccccccccccccccccccccccccccccccccccccc;,,,,,,,,ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,$cccccccccccccccccccccccccccccccccccccccccccccccc%,,,,,,,,ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,+cccccccccccccc+,,,,,,,,cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccc+,,,,,,,,ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,&cccccccccccccc%,,,,,,,,cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccc+,,,,,,,,cccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c,,,,,,,,>.ccccccccccccc:,,,,,,,,cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccc+,,,,,,,,cccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c>,,,,,,,,:&Occcccccco$>,,,,,,,,,cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccc+,,,,,,,,cccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&c*,,,,,,,,,,,$cccccc$,,,,,,,,,,,&cc,,,,,,,,+cccccccccccccccccccccccccccccccccccccccccccccccc+,,,,,,,,cccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,+ccccccccccccccccccccccccc,,,,,,,,&cc+*,,,,,,,,,,cccccc,,,,,,,,,,-#ccc,,,,,,,,#cccccccccccccccccccccccccccccccccccccccccccccccc+,,,,,,,,ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,&ccccccccccccccccccccccccc,,,,,,,,&cccc.>,,,,,,,,+cccc+,,,,,,,,,.ccccc,,,,,,,,&cccccccccccccccccccccccccccccccccccccccccccccccc*,,,,,,,,ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc,,,,,,,,>.cccccccccccccccccccccccc,,,,,,,,&ccccc*,,,,,,,,-.cc.-,,,,,,,,*cccccc,,,,,,,,>.cccccccccccccccccccccccccccccccccccccccccccccc.>,,,,,,,,cccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc>,,,,,,,,>*&&&&&&&&&&&&&&&&&&%Occc,,,,,,,,&ccccc#,,,,,,,,,>==>,,,,,,,,,+cccccc>,,,,,,,,>*&&&&&&&&&&&&&&&&&&%OccccO&&&&&&&&&&&&&&&&&&&*>,,,,,,,,,cccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccc%,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,$cc,,,,,,,,&cccccc:,,,,,,,,,,,,,,,,,,,,;ccccccc%,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,$cc&,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,$cccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccO%>,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,&ccccccc+*,,,,,,,,,,,,,,,>*OcccccccccO%>,,,,,,,,,,,,,,,,,,,,,,,,,,,;cc>,,,,,,,,,,,,,,,,,,,,,,,,,,,>&Occccccccccccccccc@,,,,,,,,,,Xccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccc.>,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,&cccccccccO,,,,,,,,,,,,,,+ccccccccccccc.>,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,,,,,,,,,,,,,,,,,,,,>.cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,&cccccccccc,,,,,,,,,,,,,>ccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,,,;cc,,,,,,,,,,,,,,,,,,,,,,,,,,,*ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"ccccccccccccccccccc+,,,,,,,,,,,,,,,,,,,,,,,,,,-cc>,,,,,,,Occcccccccc=,,,,,,,,,,,,*ccccccccccccccc+,,,,,,,,,,,,,,,,,,,,,,,,,,-cc:,,,,,,,,,,,,,,,,,,,,,,,,,,Occccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,>occO:,,,,,*ccccccccccc.;,,,,,,,,,,;.cccccccccccccccc*,,,,,,,,,,,,,,,,,,,,,,,,>occO:,,,,,,,,,,,,,,,,,,,,,,,,*cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
};

/* XPM */
static char *score[] = {
/* columns rows colors chars-per-pixel */
"98 60 11",
"c 0x000000",
". 0x191D53",
"X 0x222770",
"o 0x262B7B",
"O 0x292F85",
"+ 0x2E3597",
"@ 0x333AA6",
"# 0x373FB4",
"$ 0x3941BA",
"% 0x3B43C0",
"& 0x3F48CC",
/* pixels */
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccoOOOOOocccccccccccccccccccccccccccccccccccccccccccccccoOOOOOocccccc",
"ccccco&&&&&&&&&&&&&&ccco&&&&&&&&&&&&&&ccccO&&&&&&&&&&Occc&&&&&&&&&&&&&&XcccccO&&&&&&&&&&&&&&cccccc",
"ccccc%&&&&&&&&&&&&&&ccc%&&&&&&&&&&&&&&cccc%&&&&&&&&&&%ccc&&&&&&&&&&&&&&$ccccc%&&&&&&&&&&&&&&cccccc",
"ccco$&&&&&&&&&&&&&&&cX$&&&&&&&&&&&&&&&cco$&&&&&&&&&&&&%oc&&&&&&&&&&&&&&&#Xc+&&&&&&&&&&&&&&&&cccccc",
"ccc&&&&&%##########Oc&&&&&%##########@cc&&&&&$####$&&&&&c&&&&&%#####%&&&&&c&&&&&%##########@cccccc",
"ccc&&&&%ccccccccccccc&&&&%cccccccccccccc&&&&%cccccc$&&&&c&&&&&ccccccc%&&&&c&&&&$cccccccccccccccccc",
"ccc&&&&#ccccccccccccc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&#ccccccc#&&&&c&&&&#cccccccccccccccccc",
"ccc&&&&#ccccccccccccc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&#ccccccc#&&&&c&&&&#cccccccccccccccccc",
"ccc&&&&#ccccccccccccc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&#ccccccc#&&&&c&&&&#cccccccccccccccccc",
"ccc&&&&#ccccccccccccc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&#ccccccc#&&&&c&&&&&Xccccccccccccccccc",
"ccc&&&&&Xcccccccccccc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&&XcccccX&&&&&c&&&&&&&&&&&&&&&&&cccccc",
"ccc$&&&&&&&&&&&&&occc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&&&&&&&&&&&&&%c&&&&&&&&&&&&&&&&&cccccc",
"cccc.&&&&&&&&&&&&$ccc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&&&&&&&&&&&&Occ&&&&&&&&&&&&&&&&&cccccc",
"ccccc@&&&&&&&&&&&&$Xc&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&&&&&&&&&&&&&oc&&&&&&##########@cccccc",
"cccccc@#######%&&&&&c&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&&%#####%&&&&&c&&&&&cccccccccccccccccc",
"ccccccccccccccc%&&&&c&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&%ccccccc%&&&&c&&&&#cccccccccccccccccc",
"ccccccccccccccc#&&&&c&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&#ccccccc#&&&&c&&&&#cccccccccccccccccc",
"ccccccccccccccc#&&&&c&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&#ccccccc#&&&&c&&&&#cccccccccccccccccc",
"ccccccccccccccc#&&&&c&&&&#cccccccccccccc&&&&#cccccc#&&&&c&&&&#ccccccc#&&&&c&&&&#cccccccccccccccccc",
"ccccccccccccccc%&&&&c&&&&%cccccccccccccc&&&&$cccccc$&&&&c&&&&#ccccccc#&&&&c&&&&&cccccccccccccccccc",
"cccO##########%&&&&&c&&&&&%##########@cc&&&&&$####$&&&&&c&&&&#ccccccc#&&&&c&&&&&%##########@cccccc",
"ccc&&&&&&&&&&&&&&&$oco%&&&&&&&&&&&&&&&cco%&&&&&&&&&&&&$oc&&&&#ccccccc#&&&&co%&&&&&&&&&&&&&&&cccccc",
"ccc&&&&&&&&&&&&&&%ccccc$&&&&&&&&&&&&&&cccc%&&&&&&&&&&%ccc&&&&#ccccccc#&&&&ccc$&&&&&&&&&&&&&&cccccc",
"ccc&&&&&&&&&&&&&&occccco&&&&&&&&&&&&&&ccccO&&&&&&&&&&Occc&&&&OcccccccO&&&&ccco&&&&&&&&&&&&&&cccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"
};


/* XPM */
static char *dolar[] = {
/* columns rows colors chars-per-pixel */
"38 60 20",
"c black",
". 0x080000",
"X 0x0E0000",
"o 0x000011",
"O 0x00001F",
"+ 0x142800",
"@ 0x00282B",
"# 0x184700",
"$ 0x1D6411",
"% 0x227F1F",
"& 0x004736",
"* 0x086442",
"= 0x0E7F4C",
"- 0x22982B",
"; 0x22B136",
": 0x14984C",
"> 0x18B14C",
", 0x1DB14C",
"< 0x22B142",
"1 0x22B14C",
/* pixels */
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccc&11#cccccccccccccccc",
"cccccccccccccccccc=11-.ccccccccccccccc",
"ccccccccccccccO>111111;Xcccccccccccccc",
"cccccccccccc@,111111111111$ccccccccccc",
"ccccccccccc&111-.cO>1111111<+ccccccccc",
"ccccccccccO>11#cccco:1111111<+cccccccc",
"cccccccccc*11$ccccccO>1111111;Xccccccc",
"cccccccccc:1;Xccccccc=11111111$ccccccc",
"cccccccccc>1-.ccccccc*11111111%ccccccc",
"cccccccccc>1;Xccccccc*11111111%ccccccc",
"cccccccccc>11$ccccccc*11111111%ccccccc",
"cccccccccc>11<+cccccc*11111111%ccccccc",
"cccccccccc>111;Xccccc*11111111%ccccccc",
"cccccccccc>11111#cccc*11111111$ccccccc",
"cccccccccc>111111<+ccO>111111<+ccccccc",
"cccccccccc>11111111<+c@,11111#cccccccc",
"cccccccccc:11111111111#co:1$cccccccccc",
"cccccccccc*1111111111111#ccccccccccccc",
"ccccccccccO>11111111111111$ccccccccccc",
"ccccccccccc&111111111111111-.ccccccccc",
"cccccccccccc&111111111111111;Xcccccccc",
"ccccccccccccco:11111111111111%cccccccc",
"cccccccccccccccO>111111111111<+ccccccc",
"cccccccccccccccccO>11111111111$ccccccc",
"cccccccccccc@,1-.ccO>111111111%ccccccc",
"cccccccccco:11111<+ccO>1111111-.cccccc",
"cccccccccc*1111111;Xccc@,11111-.cccccc",
"cccccccccc:11111111#ccccc=1111-.cccccc",
"cccccccccc>11111111#cccccc*111-.cccccc",
"cccccccccc>11111111#cccccco:11-.cccccc",
"cccccccccc>11111111#ccccccc*11-.cccccc",
"cccccccccc>11111111#ccccccc*11-.cccccc",
"cccccccccc>11111111#ccccccc=11-.cccccc",
"cccccccccc:11111111$ccccccO>11%ccccccc",
"cccccccccc*111111111#ccccc*111$ccccccc",
"ccccccccccc=1111111111#cO>111-.ccccccc",
"cccccccccccc=111111111111111-.cccccccc",
"ccccccccccccc&1111111111111#cccccccccc",
"cccccccccccccccco:111111%ccccccccccccc",
"cccccccccccccccccco:11#ccccccccccccccc",
"ccccccccccccccccccc=1;Xccccccccccccccc",
"ccccccccccccccccccc&1%cccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccccccccccccccc"
};
