/* XPM */
//static char *ship1[] = {
/* columns rows colors chars-per-pixel */
/*"56 62 16",
"? 0xF7FBF7",
". 0x160134",
"X 0x071C4F",
"o 0x2B3055",
"O 0x223D7C",
"+ 0x5A6275",
"@ 0x840000",
"# 0xCF4400",
"$ 0x6f3e00",
"% 0xFFBA00",
"& 0x30639D",
"* 0x6F7992",
"= 0x3B80B6",
"- 0x4BA9D0",
"; 0x8491B1",
": 0xFFFFFF",*/
/* pixels */
/*":::::::::::::::::::::::::::..:::::::::::::::::::::::::::",
"::::::::::::::::::::::::::.+*.::::::::::::::::::::::::::",
":::::::::::::::::::::::::..+*o.:::::::::::::::::::::::::",
"::::::::::::::::::::::::.o.+**o.::::::::::::::::::::::::",
"::::::::::::::::::::::::.o.+;*o.::::::::::::::::::::::::",
"::::::.#$::::::::::::::.oo.+;*+o.::::::::::::::$$.::::::",
"::::::.oo#.::::::::::::.oo.+;*oo.::::::::::::.$o+.::::::",
"::::::.o+o.::::::::::::.o..o+*+o.::::::::::::.o+*.::::::",
"::::::.o*+.::::::::::::.oO&=-&oo.::::::::::::.o:*.::::::",
"::::::.o**.::::::::::::.O&==--=O.::::::::::::.o;*.::::::",
"::::::.o**.::::::::::::O&X#$$#X=O::::::::::::.o;o.::::::",
"::::o+?oo+.::::::::::::&X$%%%:$X&::::::::::::.o+o.+o::::",
":::+++?oo++:::::::::::o&#%%%:::#=o:::::::::::+ooo.**+:::",
"::+++o?ooo+::::::::::#o&$%#%:::$-o#::::::::::+ooo.o+;+::",
"::++?.?oo+o.::::::::@%o&$$@.%:$$-o%@::::::::.+ooo...+;::",
":++o..?oo+o.:::::::@#$o&@#%..%#@-o$#@:::::::.oo+#...o*+:",
":++...?oo+o.:::::::%#$o&O@@##@@O-o$#%:::::::.oo+o....+*:",
":+...+?oo+o.::::::.$#o&&&??o+??&-=o#$.::::::.oo;o.o..o;:",
":+..o??oo*o.::::::.$O.=&&o?++?o&--.O$.::::::.oo;o..+..;:",
":+.o?.?oo*o.::::::.@&=.&&o+??+o&=.=&@.::::::.oo;o...+.*:",
":+.?.+?oo+o.::::::.&&=.OX......XO.==O.::::::.oo;o.o...*:",
":+..o+?oo...:::$#:.&&&.XOO=--=OOX.O=&.:#$:::...oo.o+..*:",
":+.oo+?o.+o.::$$$:.&O.OOOO=--=OOOO.O&.:$$$::.oo.o.o++.*:",
":+.oo??.o+o.:#$X.....XOXXO====OXXOX.....X$#:.ooo...++.*:",
":+.o?.?oo+o.:$XOO&...OX&&X&&&&X&&XO...OOOX$:.oo+o...+.*:",
":+.?..?oo+o.:.OOO&.*.OXO&X====XO&XO.*.OOO&.:.oo+o.....*:",
":+...+?oo*o..XOOO=.*.OOXXO=--=OXXOO.*.OOO=&..oo;o.o...*:",
":+..o+?oo*o.XXOOO=.*.OOOOOOOOOOOOOO.*.OOO=&O.oo;o.o+..*:",
":+.oo+?oo&O.XXOOO=.*.O&&==O&&O===-O.*.OOO=&O.OO+o.o++.*:",
":+.oo??oO&O.XXOOO=..?O&&&=O&&O=&&=O?..OOO=&&.OOOo..++.*:",
":+.o?.?XO=&.XX......?O&&&=O&&O=&&=O?......&&.OO&X...+.*:",
":+.?..?O&-&.X.+++:.??O&&&=O&&O&&&=O??.+++:.&.OO&&.....*:",
":+..XXOO&-&..o+++;.??O$%%%OXXO$%%%O??.+++;*..OO&=OXX..*:",
":+XO&OOO&-&.oo+++*.**$&&&=%&&$&&&=%+:.+++;**.OO&-&O&OX*:",
":XO&&OO&XXX.oo+++*.*+O&&&=O&&O&&&=O+*.+++;**.XXX-&O&&&X:",
"XOO&=O&X&-&.oo+++*.*+O&&&=OXXO&&&=O+*.+++;**.OO&O=&&&=&X",
"OOO&=OXO&-&.oo+++*.++O&&&&OXXO&&&&O+*.+++;**.OO&-O=&&-=O",
"OO&&=XOO&=&.oo+ooo.++?XXXX?++?XXXX?+*.ooo**+.OO&=&X&&--&",
"OOXXXOOO&=&.ooo???.+++?XX?oooo?XX?++*.???o++.OO&-&OXXO-&",
"OXO&&OOO&=&.oo?....??+++*......*+++??....?o+.OO&=&O&&-O&",
"XOO&&OOXXXX.....@O&==O++;.oooo.;++O&&=O@.....XXXX&O&&-=O",
"OOOO&OX&&&&.oo...&&==O++;.++++.;++O&&==...oo.&&&&XO&&==&",
"OOOO&OXOOO&..oo..&&&=@++*?*;;*?*++@&&&=..oo..OOO&XO&&==&",
"OOOOOOXOOO&.?.ooo&&@@Oooo?oooo?oooO@@&=ooo.?.OOO&XOOO&=&",
"OOX.?.?OOO&.@?...&@&=O$$$?$%%$?$$$O&&@=...?@.OOO&?.?.X&&",
"O.?@?@?OOO&.#.???&@&&O..??%%%%??..O&&@&???.#.OOO&?@?@?.&",
"X.?#?#?&OO&.@.@..&&&&O++*.$%%$.*++O&&&&..@.@.&OO&?#?#?.O",
"X.?@?#?XXXX?..#..O&XXX++*.$$$$.*++XXXO&..#..?XXXX?#?@?.O",
"X.?@?@?XXXXX??@..O&++++**.#$$#.**++++O&..@??XXXXX?@?@?.X",
".XX.?.?XXXX.XO???O&oooooo......ooooooO&???OX.XXXX?.?.XX.",
":..XXXXXXXX:..OOXO&o$%%$o::::::o$%%$oO&XOO..:XXXXXXXX..:",
":::....XXXO:::...O&o%%%%o::::::o%%%%oO&...:::XXXO....:::",
":::::::.XX.:::::XO&o$%%$o::::::o$%%$oO&X:::::.XX.:::::::",
"::::::::::::::::XO&o#$$#O::::::O#$$#oO&X::::::::::::::::",
"::::::::::::::::XO&.....?::::::?.....O&X::::::::::::::::",
"::::::::::::::::XO&::::::::::::::::::O&X::::::::::::::::",
"::::::::::::::::XO&::::::::::::::::::O&X::::::::::::::::",
"::::::::::::::::?XX::::::::::::::::::XX?::::::::::::::::",
"::::::::::::::::?XX::::::::::::::::::XX?::::::::::::::::",
"::::::::::::::::?XX::::::::::::::::::XX?::::::::::::::::",
"::::::::::::::::?OX::::::::::::::::::XO?::::::::::::::::",
"::::::::::::::::?..::::::::::::::::::..?::::::::::::::::"
};*/



/* XPM */
static char *ship[] = {
/* columns rows colors chars-per-pixel */
"56 62 16",
"A 0x000000",
"B 0x800000",
"C 0x008000",
"D 0x808000",
"E 0x000080",
"F 0x800080",
"G 0x008080",
"# 0x808080",
"$ 0xC0C0C0",
"% 0xFF0000",
"& 0x00FF00",
"* 0xFFFF00",
"= 0x0000FF",
"- 0xFF00FF",
"; 0x00FFFF",
": 0xBEBEBE",
/* pixels */
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAA##AAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAA##DAAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAADA###DAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAADA###DAAAAAAAAAAAAAAAAAAAAAAAAA",
"AAAAAAA%DAAAAAAAAAAAAAAADDA####DAAAAAAAAAAAAAAADDAAAAAAA",
"AAAAAAADD%AAAAAAAAAAAAAADDA###DDAAAAAAAAAAAAAADD#AAAAAAA",
"AAAAAAAD#DAAAAAAAAAAAAAADAAD###DAAAAAAAAAAAAAAD##AAAAAAA",
"AAAAAAAD##AAAAAAAAAAAAAADDGG#GDDAAAAAAAAAAAAAAD:#AAAAAAA",
"AAAAAAAD##AAAAAAAAAAAAAADGGG##GDAAAAAAAAAAAAAAD##AAAAAAA",
"AAAAAAAD##AAAAAAAAAAAAADGD%DD%DGDAAAAAAAAAAAAAD#DAAAAAAA",
"AAAAD#ADD#AAAAAAAAAAAAAGDD***:DDGAAAAAAAAAAAAAD#DA#DAAAA",
"AAA###ADDD%AAAAAAAAAAADG%***:::%GDAAAAAAAAAAA%DDDA###AAA",
"AA###DADDDDAAAAAAAAAA%DGD*%*:::D#D%AAAAAAAAAADDDDAD###AA",
"AA##AAA%D#DAAAAAAAAAB*DGDDBA*:DD#D*BAAAAAAAAADDD%AAA##AA",
"A##DAAA%D#DAAAAAAAAB%DDGB%*AA*%B#DD%BAAAAAAAADD#%AAAD##A",
"A##AAAADD#DAAAAAAAA*%DDGDBB%%BBD#DD%*AAAAAAAADD#DAAAA##A",
"A#AAA#ADD#DAAAAAAAAD%DGGGAAD#AAG#GD%DAAAAAAAADD#DADAAD#A",
"A#AADAADD#DAAAAAAAADDAGGGDA##ADG##ADDAAAAAAAADD#DAA#AA#A",
"A#ADAAADD#DAAAAAAAABGGAGGD#AA#DGGAGGBAAAAAAAADD#DAAA#A#A",
"A#AAA#ADD#DAAAAAAAAGGGADDAAAAAADDAGGDAAAAAAAADD#DADAAA#A",
"A#AAD#ADDAAAAAAD%AAGGGADDDG##GDDDADGGAA%DAAAAAADDAD#AA#A",
"A#ADD#ADA#DAAADDDAAGDADDDDG##GDDDDADGAADDDAAADDADAD##A#A",
"A#ADDAAAD#DAA%DDAAAAADDDDDGGGGDDDDDAAAAADD%AADDDAAA##A#A",
"A#ADAAADD#DAADDDDGAAADDGGDGGGGDGGDDAAADDDDDAADD#DAAA#A#A",
"A#AAAAADD#DAAADDDGA#ADDDGDGGGGDDGDDA#ADDDGAAADD#DAAAAA#A",
"A#AAA#ADD#DAADDDDGA#ADDDDDG##GDDDDDA#ADDDGGAADD#DADAAA#A",
"A#AAD#ADD#DADDDDDGA#ADDDDDDDDDDDDDDA#ADDDGGDADD#DAD#AA#A",
"A#ADD#ADDGDADDDDDGA#ADGGGGDGGDGGG#DA#ADDDGGDADD#DAD##A#A",
"A#ADDAADDGDADDDDDGAAADGGGGDGGDGGGGDAAADDDGGGADDDDAA##A#A",
"A#ADAAADDGGADDAAAAAAADGGGGDGGDGGGGDAAAAAAAGGADDGDAAA#A#A",
"A#AAAAADG#GADA###:AAADGGGGDGGDGGGGDAAA###:AGADDGGAAAAA#A",
"A#AADDDDG#GAAD####AAADD***DDDDD***DAAA#####AADDGGDDDAA#A",
"A#DDGDDDG#GADD####A##DGGGG*GGDGGGG*#:A######ADDG#GDGDD#A",
"ADDGGDDGDDDADD####A##DGGGGDGGDGGGGD##A######ADDD#GDGGGDA",
"DDDGGDGDG#GADD####A##DGGGGDDDDGGGGD##A######ADDGDGGGGGGD",
"DDDGGDDDG#GADD####A##DGGGGDDDDGGGGD##A######ADDG#DGGG#GD",
"DDGGGDDDGGGADD#DDDA##ADDDDA##ADDDDA##ADDD###ADDGGGDGG##G",
"DDDDDDDDGGGADDDAAAA###ADDADDDDADDA###AAAAD##ADDG#GDDDD#G",
"DDDGGDDDGGGADDAAAAAAA####AAAAAA####AAAAAAAD#ADDGGGDGG#DG",
"DDDGGDDDDDDAAAAABDGGGD###ADDDDA###DGGGDBAAAAADDDDGDGG#GD",
"DDDDGDDGGGGADDAAAGGGGD###A####A###DGGGGAAADDAGGGGDDGGGGG",
"DDDDGDDDDDGAADDAAGGGGB###A####A###BGGGGAADDAADDDGDDGGGGG",
"DDDDDDDDDDGAAADDDGGBBDDDDADDDDADDDDBBGGDDDAAADDDGDDDDGGG",
"DDDAAAADDDGABAAAAGBGGDDDDAD**DADDDDGGBGAAAABADDDGAAAADGG",
"DAABABADDDGA%AAAAGBGGDAAAA****AAAADGGBGAAAA%ADDDGABABAAG",
"DAA%A%AGDDGABABAAGGGGD###AD**DA###DGGGGAABABAGDDGA%A%AAD",
"DAABA%ADDDDAAA%AADGDDD###ADDDDA###DDDDGAA%AAADDDDA%ABAAD",
"DAABABADDDDDAABAADG######A%DD%A######DGAABAADDDDDABABAAD",
"ADDAAAADDDDADDAAADGDDDDDDAAAAAADDDDDDDGAAADDADDDDAAAADDA",
"AAADDDDDDDDAAADDDDGDD**DDAAAAAADD**DDDGDDDAAADDDDDDDDAAA",
"AAAAAAADDDDAAAAAADGD****DAAAAAAD****DDGAAAAAADDDDAAAAAAA",
"AAAAAAAADDAAAAAADDGDD**DDAAAAAADD**DDDGDAAAAAADDAAAAAAAA",
"AAAAAAAAAAAAAAAADDGD%DD%DAAAAAAD%DD%DDGDAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAADDGAAAAAAAAAAAAAAAAAADGDAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAADDGAAAAAAAAAAAAAAAAAADGDAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAADDGAAAAAAAAAAAAAAAAAADGDAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAAADDAAAAAAAAAAAAAAAAA",
"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
};
