/* XPM */
static char *ship[] = {
/* columns rows colors chars-per-pixel */
"56 62 16",
"c 0x000000",
". 0x160134",
"X 0x071C4F",
"o 0x2B3055",
"O 0x223D7C",
"+ 0x5A6275",
"@ 0x840000",
"# 0xCF4400",
"$ 0xE88200",
"% 0xFFBA00",
"& 0x30639D",
"* 0x6F7992",
"= 0x3B80B6",
"- 0x4BA9D0",
"; 0x8491B1",
": 0xBEBEBE",
/* pixels */
"ccccccccccccccccccccccccccc..ccccccccccccccccccccccccccc",
"cccccccccccccccccccccccccc.+*.cccccccccccccccccccccccccc",
"ccccccccccccccccccccccccc..+*o.ccccccccccccccccccccccccc",
"cccccccccccccccccccccccc.o.+**o.cccccccccccccccccccccccc",
"cccccccccccccccccccccccc.o.+;*o.cccccccccccccccccccccccc",
"cccccc.#$cccccccccccccc.oo.+;*+o.cccccccccccccc$$.cccccc",
"cccccc.oo#.cccccccccccc.oo.+;*oo.cccccccccccc.$o+.cccccc",
"cccccc.o+o.cccccccccccc.o..o+*+o.cccccccccccc.o+*.cccccc",
"cccccc.o*+.cccccccccccc.oO&=-&oo.cccccccccccc.o:*.cccccc",
"cccccc.o**.cccccccccccc.O&==--=O.cccccccccccc.o;*.cccccc",
"cccccc.o**.ccccccccccccO&X#$$#X=Occcccccccccc.o;o.cccccc",
"cccco+coo+.cccccccccccc&X$%%%:$X&cccccccccccc.o+o.+occcc",
"ccc+++coo$#ccccccccccco&#%%%:::#=occccccccccc#$oo.**+ccc",
"cc+++oco$$$cccccccccc#o&$%#%:::$-o#cccccccccc$$$o.o+;+cc",
"cc++c.c#$+o.cccccccc@%o&$$@.%:$$-o%@cccccccc.oo$#...+;cc",
"c++o..c#o+o.ccccccc@#$o&@#%..%#@-o$#@ccccccc.oo+#...o*+c",
"c++...coo+o.ccccccc%#$o&O@@##@@O-o$#%ccccccc.oo+o....+*c",
"c+...+coo+o.cccccc.$#o&&&cco+cc&-=o#$.cccccc.oo;o.o..o;c",
"c+..occoo*o.cccccc.$O.=&&oc++co&--.O$.cccccc.oo;o..+..;c",
"c+.oc.coo*o.cccccc.@&=.&&o+cc+o&=.=&@.cccccc.oo;o...+.*c",
"c+.c.+coo+o.cccccc.&&=.OX......XO.==O.cccccc.oo;o.o...*c",
"c+..o+coo...ccc$#c.&&&.XOO=--=OOX.O=&.c#$ccc...oo.o+..*c",
"c+.oo+co.+o.cc$$$c.&O.OOOO=--=OOOO.O&.c$$$cc.oo.o.o++.*c",
"c+.oocc.o+o.c#$X.....XOXXO====OXXOX.....X$#c.ooo...++.*c",
"c+.oc.coo+o.c$XOO&...OX&&X&&&&X&&XO...OOOX$c.oo+o...+.*c",
"c+.c..coo+o.c.OOO&.*.OXO&X====XO&XO.*.OOO&.c.oo+o.....*c",
"c+...+coo*o..XOOO=.*.OOXXO=--=OXXOO.*.OOO=&..oo;o.o...*c",
"c+..o+coo*o.XXOOO=.*.OOOOOOOOOOOOOO.*.OOO=&O.oo;o.o+..*c",
"c+.oo+coo&O.XXOOO=.*.O&&==O&&O===-O.*.OOO=&O.OO+o.o++.*c",
"c+.ooccoO&O.XXOOO=..cO&&&=O&&O=&&=Oc..OOO=&&.OOOo..++.*c",
"c+.oc.cXO=&.XX......cO&&&=O&&O=&&=Oc......&&.OO&X...+.*c",
"c+.c..cO&-&.X.+++:.ccO&&&=O&&O&&&=Occ.+++:.&.OO&&.....*c",
"c+..XXOO&-&..o+++;.ccO$%%%OXXO$%%%Occ.+++;*..OO&=OXX..*c",
"c+XO&OOO&-&.oo+++*.**$&&&=%&&$&&&=%+:.+++;**.OO&-&O&OX*c",
"cXO&&OO&XXX.oo+++*.*+O&&&=O&&O&&&=O+*.+++;**.XXX-&O&&&Xc",
"XOO&=O&X&-&.oo+++*.*+O&&&=OXXO&&&=O+*.+++;**.OO&O=&&&=&X",
"OOO&=OXO&-&.oo+++*.++O&&&&OXXO&&&&O+*.+++;**.OO&-O=&&-=O",
"OO&&=XOO&=&.oo+ooo.++cXXXXc++cXXXXc+*.ooo**+.OO&=&X&&--&",
"OOXXXOOO&=&.oooccc.+++cXXcoooocXXc++*.ccco++.OO&-&OXXO-&",
"OXO&&OOO&=&.ooc....cc+++*......*+++cc....co+.OO&=&O&&-O&",
"XOO&&OOXXXX.....@O&==O++;.oooo.;++O&&=O@.....XXXX&O&&-=O",
"OOOO&OX&&&&.oo...&&==O++;.++++.;++O&&==...oo.&&&&XO&&==&",
"OOOO&OXOOO&..oo..&&&=@++*c*;;*c*++@&&&=..oo..OOO&XO&&==&",
"OOOOOOXOOO&.c.ooo&&@@OooocoooocoooO@@&=ooo.c.OOO&XOOO&=&",
"OOX.c.cOOO&.@c...&@&=O$$$c$%%$c$$$O&&@=...c@.OOO&c.c.X&&",
"O.c@c@cOOO&.#.ccc&@&&O..cc%%%%cc..O&&@&ccc.#.OOO&c@c@c.&",
"X.c#c#c&OO&.@.@..&&&&O++*.$%%$.*++O&&&&..@.@.&OO&c#c#c.O",
"X.c@c#cXXXXc..#..O&XXX++*.$$$$.*++XXXO&..#..cXXXXc#c@c.O",
"X.c@c@cXXXXXcc@..O&++++**.#$$#.**++++O&..@ccXXXXXc@c@c.X",
".XX.c.cXXXX.XOcccO&oooooo......ooooooO&cccOX.XXXXc.c.XX.",
"c..XXXXXXXXc..OOXO&o$%%$occcccco$%%$oO&XOO..cXXXXXXXX..c",
"ccc....XXXOccc...O&o%%%%occcccco%%%%oO&...cccXXXO....ccc",
"ccccccc.XX.cccccXO&o$%%$occcccco$%%$oO&Xccccc.XX.ccccccc",
"ccccccccccccccccXO&o#$$#OccccccO#$$#oO&Xcccccccccccccccc",
"ccccccccccccccccXO&.....cccccccc.....O&Xcccccccccccccccc",
"ccccccccccccccccXO&ccccccccccccccccccO&Xcccccccccccccccc",
"ccccccccccccccccXO&ccccccccccccccccccO&Xcccccccccccccccc",
"cccccccccccccccccXXccccccccccccccccccXXccccccccccccccccc",
"cccccccccccccccccXXccccccccccccccccccXXccccccccccccccccc",
"cccccccccccccccccXXccccccccccccccccccXXccccccccccccccccc",
"cccccccccccccccccOXccccccccccccccccccXOccccccccccccccccc",
"ccccccccccccccccc..cccccccccccccccccc..ccccccccccccccccc"
};
